/* LOTHEM Vendas — dados de demonstração.
   Tudo aqui é fictício: pessoas, empresas, telefones, valores e preços.
   Data de referência da demo: quarta-feira, 07/10/2026, 10:24. */

const DEMO_NOW = { label: 'Quarta, 7 de outubro', time: '10:24', day: 7, daysInMonth: 31 };

const DB = {
  me: 'u1',

  users: [
    { id: 'u1', name: 'Rebeca Macedo', short: 'Rebeca', email: 'rebeca@lothem.com.br', phone: '(11) 90000-0101', role: 'Proprietária', fn: 'Estratégia e diagnósticos', squad: 'fec', xp: 10780, seasonXp: 1420, color: '#1f9fd6', status: 'ativo', last: 'agora', twofa: true, orgs: ['mkt', 'cred', 'pf'], kpi: { nm: 'Diagnósticos realizados', v: 7, goal: 28 } },
    { id: 'u2', name: 'Caio Duarte', short: 'Caio', email: 'caio@lothem.com.br', phone: '(11) 90000-0102', role: 'Closer', fn: 'Fechamento de consultorias', squad: 'fec', xp: 6940, seasonXp: 980, color: '#7a5cf0', status: 'ativo', last: 'há 4 min', twofa: true, orgs: ['mkt'], kpi: { nm: 'Consultorias fechadas', v: 1, goal: 6 } },
    { id: 'u3', name: 'Marina Alves', short: 'Marina', email: 'marina@lothem.com.br', phone: '(11) 90000-0103', role: 'SDR', fn: 'Pré-vendas e supervisão da Cibelle', squad: 'aq', xp: 4610, seasonXp: 1360, color: '#e0577f', status: 'ativo', last: 'há 1 min', twofa: false, orgs: ['mkt', 'cred', 'pf'], kpi: { nm: 'Diagnósticos vendidos', v: 10, goal: 32 } },
    { id: 'u4', name: 'Thiago Reis', short: 'Thiago', email: 'thiago@lothem.com.br', phone: '(11) 90000-0104', role: 'Tráfego', fn: 'Meta Ads e criativos', squad: 'aq', xp: 3180, seasonXp: 1110, color: '#1aa874', status: 'ativo', last: 'há 26 min', twofa: true, orgs: ['mkt'], kpi: { nm: 'Leads qualificados', v: 25, goal: 96 } },
  ],

  /* Meta pessoal: quanto cada pessoa quer ganhar e como ela é paga (valores fictícios).
     pay = R$ por unidade da etapa · pct = % sobre o valor da etapa. */
  comp: {
    mkt: {
      u1: { wish: 22000, label: 'Pró-labore', fixo: 0, pct: { diag: 0.3, cons: 0.3 }, note: '30% da receita vira pró-labore depois dos custos' },
      u2: { wish: 7000, label: 'Salário', fixo: 2500, pct: { cons: 0.07 }, note: 'Fixo + 7% de cada consultoria fechada' },
      u3: { wish: 4000, label: 'Salário', fixo: 2000, pay: { diag: 35, cons: 150 }, note: 'Fixo + R$ 35 por diagnóstico vendido + R$ 150 por consultoria que nasceu dele' },
      u4: { wish: 5000, label: 'Salário', fixo: 3000, pay: { qual: 15 }, note: 'Fixo + R$ 15 por lead qualificado' },
    },
    cred: {
      u1: { wish: 12000, label: 'Pró-labore', fixo: 0, pct: { contratado: 0.012 }, note: '1,2% do volume contratado' },
      u3: { wish: 2500, label: 'Comissão extra', fixo: 0, pay: { perfil: 60, contratado: 300 }, note: 'R$ 60 por perfil analisado + R$ 300 por contrato' },
    },
    pf: {
      u1: { wish: 8000, label: 'Pró-labore', fixo: 0, pct: { contratado: 0.025 }, note: '2,5% do valor contratado' },
      u3: { wish: 2000, label: 'Comissão extra', fixo: 0, pay: { simulacao: 12, contratado: 150 }, note: 'R$ 12 por simulação + R$ 150 por contrato' },
    },
  },

  squads: {
    aq: { name: 'Squad Aquisição', desc: 'Tráfego, SDR humana e Cibelle (IA)', color: 'cy' },
    fec: { name: 'Squad Fechamento', desc: 'Diagnóstico e consultoria', color: 'gold' },
  },

  invites: [
    { id: 'inv1', email: 'fernanda.k@exemplo.com', role: 'Closer', squad: 'fec', orgs: ['mkt'], sent: 'há 2 dias', expires: 'expira em 5 dias', by: 'u1' },
    { id: 'inv2', email: 'joao.pedro@exemplo.com', role: 'SDR', squad: 'aq', orgs: ['cred'], sent: 'ontem', expires: 'expira em 6 dias', by: 'u1' },
  ],

  roles: ['Proprietária', 'Gestor', 'Closer', 'SDR', 'Tráfego', 'Leitor'],
  modules: [
    { k: 'central', nm: 'Central (dashboard)', p: ['total', 'total', 'ver', 'ver', 'ver', 'ver'] },
    { k: 'atend', nm: 'Atendimento WhatsApp', p: ['total', 'total', 'editar', 'editar', 'ver', '—'] },
    { k: 'funis', nm: 'Funis e negócios', p: ['total', 'total', 'editar', 'editar', 'ver', 'ver'] },
    { k: 'contatos', nm: 'Contatos e empresas', p: ['total', 'total', 'editar', 'editar', 'ver', 'ver'] },
    { k: 'tarefas', nm: 'Tarefas e agenda', p: ['total', 'total', 'editar', 'editar', 'editar', 'ver'] },
    { k: 'sdr', nm: 'SDR IA · treinamento', p: ['total', 'editar', 'ver', 'editar', '—', '—'] },
    { k: 'chat', nm: 'Chat da equipe', p: ['total', 'total', 'editar', 'editar', 'editar', 'ver'] },
    { k: 'evol', nm: 'Evolução e ranking', p: ['total', 'total', 'ver', 'ver', 'ver', 'ver'] },
    { k: 'meta', nm: 'Meta pessoal de outras pessoas', p: ['total', 'total', '—', '—', '—', '—'] },
    { k: 'canais', nm: 'Canais e integrações', p: ['total', 'editar', '—', 'ver', '—', '—'] },
    { k: 'equipe', nm: 'Equipe e acessos', p: ['total', 'editar', '—', '—', '—', '—'] },
    { k: 'planos', nm: 'Planos e pagamentos', p: ['total', '—', '—', '—', '—', '—'] },
    { k: 'export', nm: 'Exportar dados', p: ['total', 'editar', '—', '—', '—', '—'] },
  ],
  scopes: [
    { nm: 'Vê apenas os próprios negócios', roles: [false, false, true, true, false, false] },
    { nm: 'Pode assumir conversa da IA', roles: [true, true, true, true, false, false] },
    { nm: 'Pode apagar registros', roles: [true, false, false, false, false, false] },
  ],

  plans: [
    { id: 'ess', nm: 'Essencial', price: 189, tag: 'Para começar', feats: ['3 usuários', '1 instância WhatsApp', '1 funil de vendas', 'Gamificação básica', 'Sem SDR IA'] },
    { id: 'pro', nm: 'Profissional', price: 449, tag: 'Plano atual', feats: ['10 usuários', '3 instâncias WhatsApp (oficial ou não oficial)', 'Funis ilimitados', 'SDR IA com 2.000 conversas/mês', 'Gamificação completa e desafios', '3 organizações'] },
    { id: 'ag', nm: 'Agência', price: 1190, tag: 'Multiorganização', feats: ['25 usuários', '10 instâncias WhatsApp', 'Organizações ilimitadas', 'SDR IA com 10.000 conversas/mês', 'Uma SDR IA treinada por organização', 'Relatórios por cliente e marca branca'] },
  ],
  billing: {
    plan: 'pro', cycle: 'mensal', next: '15/10/2026', card: 'Cartão final 4821', holder: 'Lothem Inteligência em Marketing',
    usage: [
      { nm: 'Usuários', v: 6, max: 10, note: '4 ativos + 2 convites' },
      { nm: 'Instâncias WhatsApp', v: 3, max: 3, note: 'no limite do plano' },
      { nm: 'Conversas da SDR IA', v: 1742, max: 2000, note: 'ciclo 15/09 a 14/10' },
      { nm: 'Organizações', v: 3, max: 3, note: 'Marketing, Crédito PJ e Crédito PF' },
    ],
    invoices: [
      { id: 'NF 2026/0912', date: '15/09/2026', desc: 'Profissional · mensal', v: 449, st: 'Paga' },
      { id: 'NF 2026/0815', date: '15/08/2026', desc: 'Profissional · mensal', v: 449, st: 'Paga' },
      { id: 'NF 2026/0716', date: '15/07/2026', desc: 'Profissional · mensal', v: 449, st: 'Paga' },
      { id: 'NF 2026/0618', date: '15/06/2026', desc: 'Upgrade Essencial → Profissional (proporcional)', v: 216.4, st: 'Paga' },
    ],
    addons: [
      { nm: '+1.000 conversas da SDR IA', v: 129 },
      { nm: '+1 instância WhatsApp', v: 79 },
    ],
  },

  tickets: [
    { id: 1042, t: 'Instância "Closer · Caio" desconecta sozinha', cat: 'Canais WhatsApp', pri: 'Alta', st: 'Em andamento', upd: 'há 2 h', by: 'u2', last: 'Suporte: identificamos que o celular do Caio entra em economia de bateria. Enviamos o passo a passo para desativar.' },
    { id: 1038, t: 'Template reativacao_15d em análise há 3 dias', cat: 'Templates', pri: 'Média', st: 'Aguardando você', upd: 'ontem', by: 'u1', last: 'Suporte: a Meta pediu para tirar a palavra "promoção". Pode aprovar a nova versão?' },
    { id: 1031, t: 'Como enviar o evento "diagnóstico pago" para a Meta?', cat: 'Integrações', pri: 'Baixa', st: 'Resolvido', upd: '02/10', by: 'u4', last: 'Resolvido: evento Purchase configurado na API de Conversões.' },
  ],
  services: [
    { nm: 'WhatsApp · API oficial (Cloud API)', st: 'ok', note: 'Operacional' },
    { nm: 'WhatsApp · conexão por QR Code', st: 'warn', note: 'Instável em alguns aparelhos Android', bars: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0] },
    { nm: 'SDR IA', st: 'ok', note: 'Operacional' },
    { nm: 'Meta Lead Ads e API de Conversões', st: 'ok', note: 'Operacional' },
    { nm: 'Pagamentos (Pix e cartão)', st: 'ok', note: 'Operacional' },
  ],
  helpArticles: [
    'Como conectar uma instância por QR Code',
    'API oficial ou não oficial: qual usar em cada caso',
    'Boas práticas para não ter o número bloqueado',
    'Como treinar a SDR IA com artigos e áudios',
    'Como a pontuação da Evolução é calculada',
    'Convites, funções e permissões',
  ],

  notifications: [
    { id: 'n1', ic: 'UserCheck', cls: 'bad', t: 'Juliana Torres pediu atendimento humano', d: 'Ritmo Fit · SLA de transferência de 10 min correndo', go: 'atendimento', cv: 'cv7', unread: true },
    { id: 'n2', ic: 'CircleDollarSign', cls: 'ok', t: 'Pagamento confirmado · R$ 497', d: 'Ana Beatriz Lima · diagnóstico de sexta', go: 'funis', unread: true },
    { id: 'n3', ic: 'WifiOff', cls: 'warn', t: 'Instância "Closer · Caio" desconectada', d: 'Leia o QR Code de novo para reconectar', go: 'canais', unread: true },
    { id: 'n4', ic: 'Award', cls: 'gold', t: 'Conquista desbloqueada: Treinadora II', d: '50 correções aprovadas na Cibelle', go: 'evolucao', unread: false },
    { id: 'n5', ic: 'Handshake', cls: 'cy', t: 'Cibelle preparou o handoff de Fernanda Lopes', d: 'Lopes Arquitetura · revise antes de atribuir', go: 'chat', unread: false },
  ],

  game: {
    season: { nm: 'Temporada Q4 · 2026', ends: '31/12', daysLeft: 85 },
    streak: 12, streakBest: 19,
    rules: [
      { a: 'Responder lead dentro do SLA definido pela gestão', xp: 5, cap: '40 por dia' },
      { a: 'Concluir tarefa no prazo', xp: 10, cap: '20 por dia' },
      { a: 'Follow-up feito no dia combinado', xp: 5, cap: '30 por dia' },
      { a: 'Corrigir ou aprovar resposta da SDR IA', xp: 15, cap: '30 por dia' },
      { a: 'Atualizar negócio parado há mais de 10 dias', xp: 8, cap: '15 por dia' },
      { a: 'Lead qualificado (você ou a IA que você supervisiona)', xp: 25, cap: 'sem limite' },
      { a: 'Diagnóstico vendido (pagamento confirmado)', xp: 80, cap: 'sem limite' },
      { a: 'Diagnóstico realizado com resumo entregue em 24 h', xp: 60, cap: 'sem limite' },
      { a: 'Consultoria fechada (contrato assinado)', xp: 300, cap: 'sem limite' },
    ],
    achievements: [
      { ic: 'Handshake', nm: 'Primeira consultoria', d: 'Fechar a primeira consultoria da conta', tier: 'ÚNICA', got: true, when: 'mar/2026' },
      { ic: 'Timer', nm: 'Speed-to-lead', d: '95% dos leads respondidos em até 5 min por 30 dias', tier: 'NÍVEL I', got: true, when: 'set/2026' },
      { ic: 'GraduationCap', nm: 'Treinadora', d: 'Correções aprovadas na SDR IA', tier: 'NÍVEL II', got: true, when: 'out/2026', prog: [52, 150], next: 'Nível III' },
      { ic: 'CalendarCheck', nm: 'Agenda cheia', d: '20 diagnósticos realizados em um mês', tier: 'NÍVEL I', got: true, when: 'set/2026' },
      { ic: 'Flame', nm: 'Ritmo 30', d: '30 dias seguidos batendo o mínimo diário', tier: 'BLOQUEADA', got: false, prog: [12, 30] },
      { ic: 'ListChecks', nm: 'Sem pendências', d: '10 dias seguidos sem tarefa atrasada', tier: 'BLOQUEADA', got: false, prog: [0, 10] },
      { ic: 'Gauge', nm: 'Show-up 90', d: '90% de comparecimento nos diagnósticos do mês', tier: 'BLOQUEADA', got: false, prog: [82, 90], unit: '%' },
      { ic: 'Repeat', nm: 'Recuperação', d: '5 leads frios reativados que viraram diagnóstico', tier: 'BLOQUEADA', got: false, prog: [3, 5] },
      { ic: 'Crown', nm: 'Ticket alto', d: 'Fechar uma consultoria acima de R$ 15.000', tier: 'BLOQUEADA', got: false, prog: [0, 1] },
      { ic: 'Target', nm: 'Proposta certeira', d: '30% de fechamento em 20 propostas seguidas', tier: 'BLOQUEADA', got: false, prog: [11, 20] },
      { ic: 'Workflow', nm: 'Pipeline limpo', d: 'Nenhum negócio parado há mais de 14 dias', tier: 'BLOQUEADA', got: false, prog: [4, 0], inv: true },
      { ic: 'Users', nm: 'Meta em dupla', d: 'Os dois squads batem a meta do mês juntos', tier: 'EQUIPE', got: false, prog: [0, 1] },
    ],
    challenges: [
      { id: 'ch1', nm: 'Objeção de preço', scope: 'Individual', who: 'u1', d: 'Ensinar 5 respostas aprovadas de objeção de preço para a Cibelle.', v: 2, goal: 5, xp: 150, left: '5 dias', go: 'sdr', joined: true },
      { id: 'ch2', nm: 'Semana do show-up', scope: 'Squad Fechamento', who: 'fec', d: '90% de comparecimento nos diagnósticos desta semana.', v: 8, goal: 9, xp: 200, left: '3 dias', unit: 'compareceram', joined: true },
      { id: 'ch3', nm: 'Limpeza de pipeline', scope: 'Individual', who: 'u1', d: 'Atualizar 8 negócios parados há mais de 10 dias.', v: 3, goal: 8, xp: 120, left: '6 dias', go: 'funis', joined: true },
      { id: 'ch4', nm: 'Corrida da consultoria', scope: 'Equipe toda', who: 'all', d: 'Fechar 6 consultorias até 31/10.', v: 1, goal: 6, xp: 500, left: '24 dias', go: 'funis', joined: true },
      { id: 'ch5', nm: 'Reativação de outubro', scope: 'Individual', who: null, d: 'Recuperar 5 leads frios com mensagem nova (nada de "e aí, viu?").', v: 0, goal: 5, xp: 180, left: '24 dias', joined: false },
      { id: 'ch6', nm: 'Follow-up D+2', scope: 'Individual', who: null, d: '20 follow-ups feitos no dia certo, com valor novo.', v: 0, goal: 20, xp: 120, left: '14 dias', joined: false },
    ],
    rewards: [
      { nm: 'Folga de um dia', crit: 'Bater 100% da meta individual no mês' },
      { nm: 'Curso à escolha (até R$ 600)', crit: 'Fechar a temporada no nível Estratégia ou acima' },
      { nm: 'Bônus de squad', crit: 'Os dois squads batem a meta do trimestre' },
    ],
  },

  orgs: {
    /* ======================= LOTHEM — MARKETING ======================= */
    mkt: {
      id: 'mkt', name: 'LOTHEM — Inteligência em Marketing', short: 'Lothem Marketing', mark: 'LM', hue: 'cy',
      plan: 'Profissional', members: ['u1', 'u2', 'u3', 'u4'],
      sla: { primeira: 5, transfer: 10, retorno: 15, followup: 24, warnAt: 80, business: true, notifyBoss: true, redistribute: false, iaHold: true, roles: ['SDR', 'Closer'] },
      autofill: {
        on: true, minConf: 80,
        fields: [
          { k: 'cadastro', nm: 'Cadastro do contato', d: 'Empresa, segmento, cidade e e-mail que o lead conta na conversa.', on: true },
          { k: 'qualif', nm: 'Qualificação', d: 'Dor, decisor, momento e capacidade, com o trecho da conversa como prova.', on: true },
          { k: 'score', nm: 'Pontuação e temperatura', d: 'Recalcula a cada resposta do lead.', on: true },
          { k: 'etapa', nm: 'Etapa do funil e próximo passo', d: 'Move o negócio quando a conversa avança.', on: true },
          { k: 'task', nm: 'Tarefas e agenda', d: 'Cria a tarefa do diagnóstico ou da reunião combinada.', on: true },
        ],
        never: ['CPF, RG e fotos de documentos', 'Dados bancários e de cartão', 'Faturamento que o lead não confirmou'],
        stats: { today: 46, corrected: 2 },
        log: [
          { id: 'l1', t: '10:09', cv: 'cv2', c: 'c12', k: 'dor', nm: 'Dor', value: 'Site tem visita, mas converte 0,4%.', quote: 'A conversão tá em 0,4%', conf: 95, by: 'ia' },
          { id: 'l2', t: '10:05', cv: 'cv2', c: 'c12', k: 'seg', nm: 'Segmento', value: 'E-commerce de moda', quote: 'Tenho um e-commerce de moda feminina', conf: 97, by: 'ia' },
          { id: 'l3', t: '09:52', cv: 'cv1', c: 'c2', k: 'capacidade', nm: 'Capacidade', value: 'Já investiu R$ 4 mil com agência, sem retorno.', quote: 'Gastei 4 mil e não veio nada', conf: 94, by: 'ia' },
          { id: 'l4', t: '09:44', cv: 'cv1', c: 'c2', k: 'city', nm: 'Cidade', value: 'Guarulhos/SP', quote: 'loja de móveis planejados em Guarulhos', conf: 98, by: 'ia' },
          { id: 'l5', t: '09:44', cv: 'cv1', c: 'c2', k: 'dor', nm: 'Dor', value: 'Movimento caiu; Instagram não vende; depende de indicação e arquiteto.', quote: 'O movimento caiu muito esse ano', conf: 91, by: 'ia' },
          { id: 'l6', t: '09:40', cv: 'cv7', c: 'c4', k: 'capacidade', nm: 'Capacidade', value: 'Investe R$ 800/mês em impulsionamento.', quote: 'impulsiono uns 800 por mês', conf: 93, by: 'ia' },
          { id: 'l7', t: '08:31', cv: 'cv3', c: 'c10', k: 'task', nm: 'Tarefa', value: 'Diagnóstico sex 09/10, 11:00 · Rebeca', quote: 'Sexta, 09/10, às 11h com a Rebeca', conf: 97, by: 'ia' },
          { id: 'l8', t: '08:30', cv: 'cv3', c: 'c10', k: 'etapa', nm: 'Etapa do funil', value: 'Diagnóstico ofertado', quote: 'Pode ser sexta às 11h?', conf: 96, by: 'ia' },
        ],
      },
      slaStats: [
        { u: 'u3', convs: 184, inSla: 94, avg: '3 min 48 s', breaches: 11 },
        { u: 'u2', convs: 61, inSla: 88, avg: '6 min 10 s', breaches: 7 },
        { u: 'u1', convs: 47, inSla: 97, avg: '2 min 05 s', breaches: 1 },
        { u: 'ia', convs: 238, inSla: 100, avg: '41 s', breaches: 0 },
      ],
      ia: { name: 'Cibelle', role: 'SDR IA', mode: 'sup', offer: 'Diagnóstico Estratégico de Marketing', price: 497 },
      /* Rota comercial: cada etapa converte para a próxima com a taxa r (últimos 30 dias). mtd = feito em outubro até hoje. */
      route: {
        cpl: 28.74, outbound: 28, rateNote: 'Taxas dos últimos 30 dias · ticket médio da consultoria R$ 11.000 (fictício)',
        steps: [
          { k: 'leads', nm: 'Leads do Meta', ic: 'Megaphone', who: ['u4'], mtd: 61, r: 0.403, verb: 'viram qualificados' },
          { k: 'qual', nm: 'Leads qualificados', one: 'lead qualificado', ic: 'ListChecks', who: ['ia', 'u3'], mtd: 25, r: 0.396, verb: 'compram o diagnóstico' },
          { k: 'diag', nm: 'Diagnósticos vendidos', one: 'diagnóstico vendido', ic: 'CircleDollarSign', who: ['u3', 'ia'], mtd: 10, r: 0.816, value: 497, verb: 'comparecem' },
          { k: 'real', nm: 'Diagnósticos realizados', ic: 'Video', who: ['u1'], mtd: 7, r: 0.71, verb: 'viram reunião com o Closer' },
          { k: 'reun', nm: 'Reuniões do Closer', ic: 'Handshake', who: ['u2'], mtd: 5, r: 0.227, verb: 'fecham a consultoria' },
          { k: 'cons', nm: 'Consultorias fechadas', one: 'consultoria fechada', ic: 'BadgeCheck', who: ['u2'], mtd: 1, value: 11000 },
        ],
        sdr: 'u3', closer: 'u2', sdrStep: 'diag', closerStep: 'cons', closerPrep: 'reun',
      },

      metrics: {
        goalLabel: 'Receita de outubro', goal: 60000, done: 14770, money: true,
        revDaily: [497, 994, 497, 994, 497, 10794, 497],
        kpis: [
          { k: 'Leads do Meta', v: '61', sub: 'no mês', delta: 12, spark: [9, 10, 8, 9, 8, 10, 7], go: 'atendimento', hint: 'CPL médio R$ 28,74' },
          { k: 'Qualificação pela IA', v: '41', unit: '%', delta: 3, spark: [36, 38, 37, 40, 39, 42, 41], go: 'sdr', hint: '25 qualificados' },
          { k: 'Diagnósticos vendidos', v: '10', sub: 'de 40', delta: 8, spark: [1, 2, 1, 2, 1, 2, 1], go: 'funis', hint: 'R$ 4.970 em Pix' },
          { k: 'Comparecimento', v: '82', unit: '%', delta: -4, spark: [88, 86, 85, 84, 83, 82, 82], go: 'tarefas', hint: 'meta 85%' },
          { k: 'Consultorias fechadas', v: '1', sub: 'de 6', delta: 0, spark: [0, 0, 0, 0, 0, 1, 1], go: 'funis', hint: 'R$ 9.800 · Fontes Idiomas' },
          { k: 'Primeira resposta', v: '41', unit: 's', delta: 9, spark: [58, 52, 49, 47, 44, 43, 41], go: 'sdr', hint: 'mediana · Cibelle', invert: true },
        ],
        funnel: [
          { nm: 'Leads do Meta', v: 238 },
          { nm: 'Qualificados pela IA', v: 96 },
          { nm: 'Diagnóstico vendido', v: 38 },
          { nm: 'Diagnóstico realizado', v: 31 },
          { nm: 'Consultoria fechada', v: 5, gold: true },
        ],
        funnelNote: 'Últimos 30 dias · investimento R$ 6.840 · custo por consultoria R$ 1.368',
        series: {
          a: [6, 8, 7, 9, 5, 4, 7, 8, 10, 9, 8, 6, 5, 9, 9, 10, 8, 7, 6, 9, 10, 9, 8, 9, 10, 8, 9, 8, 10, 7],
          b: [2, 3, 3, 4, 2, 1, 3, 3, 4, 4, 3, 2, 2, 4, 4, 4, 3, 3, 2, 4, 4, 4, 3, 4, 4, 3, 4, 3, 4, 3],
          la: 'Leads', lb: 'Qualificados', start: [8, 9],
        },
        campaigns: [
          { nm: '[CAPT] Diagnóstico · Vídeo Rebeca 45s', inv: 2910, leads: 112, q: 51, d: 21, c: 4 },
          { nm: '[CAPT] Carrossel · Post todo dia e nada de cliente', inv: 1870, leads: 74, q: 24, d: 9, c: 1 },
          { nm: '[CAPT] Estático · Checklist do empresário', inv: 1240, leads: 34, q: 11, d: 4, c: 0 },
          { nm: '[REMKT] Visitantes da LP · 30 dias', inv: 820, leads: 18, q: 10, d: 4, c: 0 },
        ],
        insight: 'O vídeo da Rebeca gera diagnóstico 23% mais barato que a média (R$ 138 contra R$ 180). Vale mover parte da verba do estático para ele.',
        ia: { active: 7, handoffs: 1, reviews: 6, conf: 87, resp: '41 s', csat: '4,7' },
        ticker: [
          { t: '10:19', x: 'Cibelle iniciou conversa com <b>Bruno Carvalho</b> · Carvalho Burger' },
          { t: '10:16', x: '<b>Juliana Torres</b> pediu atendimento humano', cls: 'bad' },
          { t: '10:09', x: 'Cibelle registrou a dor de <b>Priscila Antunes</b>: conversão do site em 0,4%' },
          { t: '09:53', x: 'Resposta para <b>Rodrigo Menezes</b> enviada para revisão (confiança 58%)', cls: 'warn' },
          { t: '08:31', x: 'Link do diagnóstico enviado para <b>Renata Siqueira</b>' },
        ],
        alerts: [
          { cls: 'bad', ic: 'UserCheck', t: 'Juliana Torres espera atendimento humano há 12 min', go: 'atendimento', cv: 'cv7' },
          { cls: 'warn', ic: 'WifiOff', t: 'Instância "Closer · Caio" desconectada', go: 'canais' },
          { cls: 'warn', ic: 'ClockAlert', t: '2 tarefas atrasadas', go: 'tarefas' },
          { cls: 'cy', ic: 'GraduationCap', t: '6 respostas da Cibelle esperam revisão', go: 'sdr', tab: 'rev' },
        ],
      },

      pipelines: [
        { id: 'inb', nm: 'Inbound · Diagnóstico', desc: 'Lead do Meta até o diagnóstico realizado', stages: [
          { id: 'novo', nm: 'Novo lead', p: 5 }, { id: 'conversa', nm: 'Em conversa · IA', p: 10 }, { id: 'qualificado', nm: 'Qualificado', p: 30 },
          { id: 'ofertado', nm: 'Diagnóstico ofertado', p: 50 }, { id: 'pago', nm: 'Diagnóstico pago', p: 90 }, { id: 'realizado', nm: 'Diagnóstico realizado', p: 100, won: true } ] },
        { id: 'cons', nm: 'Consultoria · Closer', desc: 'Do handoff ao contrato assinado', stages: [
          { id: 'handoff', nm: 'Handoff recebido', p: 15 }, { id: 'reuniao', nm: 'Reunião agendada', p: 30 }, { id: 'proposta', nm: 'Proposta enviada', p: 50 },
          { id: 'negociacao', nm: 'Negociação', p: 70 }, { id: 'ganho', nm: 'Ganho', p: 100, won: true }, { id: 'perdido', nm: 'Perdido', p: 0, lost: true } ] },
        { id: 'out', nm: 'Outbound · Prospector', desc: 'Leads do Google Maps em cadência de 14 dias', stages: [
          { id: 'importado', nm: 'Importado', p: 3 }, { id: 'cadencia', nm: 'Em cadência', p: 8 }, { id: 'respondeu', nm: 'Respondeu', p: 20 }, { id: 'reuniao', nm: 'Reunião marcada', p: 40 } ] },
      ],

      contacts: [
        { id: 'c1', nm: 'Ana Beatriz Lima', co: 'Clínica Sorriso Pleno', seg: 'Odontologia', city: 'Santo André/SP', ph: '(11) 90000-1101', em: 'ana@sorrisopleno.exemplo', src: 'Meta · Vídeo Rebeca', owner: 'u1', life: 'Cliente diagnóstico', score: 88, last: 'hoje 08:26' },
        { id: 'c2', nm: 'Rodrigo Menezes', co: 'Menezes Móveis Planejados', seg: 'Móveis planejados', city: 'Guarulhos/SP', ph: '(11) 90000-1102', em: 'rodrigo@menezesmoveis.exemplo', src: 'Meta · Carrossel', owner: 'u3', life: 'Lead', score: 54, last: 'hoje 09:53' },
        { id: 'c3', nm: 'Felipe Costa', co: 'Costa & Prado Contabilidade', seg: 'Contabilidade', city: 'São Paulo/SP', ph: '(11) 90000-1103', em: 'felipe@costaprado.exemplo', src: 'Meta · Vídeo Rebeca', owner: 'u2', life: 'Cliente diagnóstico', score: 91, last: 'hoje 09:31' },
        { id: 'c4', nm: 'Juliana Torres', co: 'Academia Ritmo Fit', seg: 'Academia', city: 'Osasco/SP', ph: '(11) 90000-1104', em: 'juliana@ritmofit.exemplo', src: 'Meta · Estático', owner: 'u3', life: 'Qualificado', score: 72, last: 'hoje 10:16' },
        { id: 'c5', nm: 'Marcos Vieira', co: 'Vieira Construtora', seg: 'Construção civil', city: 'Sorocaba/SP', ph: '(15) 90000-1105', em: 'marcos@vieiraconstrutora.exemplo', src: 'Indicação', owner: 'u2', life: 'Cliente diagnóstico', score: 84, last: 'seg 16:40' },
        { id: 'c6', nm: 'Camila Rocha', co: 'Bella Pele Estética', seg: 'Estética', city: 'São Bernardo/SP', ph: '(11) 90000-1106', em: 'camila@bellapele.exemplo', src: 'Meta · Vídeo Rebeca', owner: 'u2', life: 'Cliente diagnóstico', score: 86, last: 'ontem 18:02' },
        { id: 'c7', nm: 'Eduardo Nogueira', co: 'Nogueira Imóveis', seg: 'Imobiliária', city: 'Santos/SP', ph: '(13) 90000-1107', em: 'eduardo@nogueiraimoveis.exemplo', src: 'Meta · Remarketing', owner: 'u2', life: 'Cliente diagnóstico', score: 79, last: 'ontem 11:15' },
        { id: 'c8', nm: 'Larissa Fontes', co: 'Fontes Idiomas', seg: 'Escola de idiomas', city: 'Campinas/SP', ph: '(19) 90000-1108', em: 'larissa@fontesidiomas.exemplo', src: 'Meta · Vídeo Rebeca', owner: 'u2', life: 'Cliente consultoria', score: 95, last: 'ontem 15:20' },
        { id: 'c9', nm: 'Gustavo Almeida', co: 'Oficina Almeida Car', seg: 'Oficina mecânica', city: 'Mauá/SP', ph: '(11) 90000-1109', em: 'contato@almeidacar.exemplo', src: 'Prospector · Google Maps', owner: 'u3', life: 'Lead', score: 63, last: 'hoje 09:58' },
        { id: 'c10', nm: 'Renata Siqueira', co: 'Pet Feliz Banho & Tosa', seg: 'Pet shop', city: 'Jundiaí/SP', ph: '(11) 90000-1110', em: 'renata@petfeliz.exemplo', src: 'Meta · Carrossel', owner: 'u3', life: 'Qualificado', score: 77, last: 'hoje 08:31' },
        { id: 'c11', nm: 'Bruno Carvalho', co: 'Carvalho Burger', seg: 'Restaurante', city: 'São Paulo/SP', ph: '(11) 90000-1111', em: 'bruno@carvalhoburger.exemplo', src: 'Meta · Estático', owner: 'u3', life: 'Lead', score: 30, last: 'hoje 10:19' },
        { id: 'c12', nm: 'Priscila Antunes', co: 'Moda Prisma', seg: 'E-commerce de moda', city: 'São Paulo/SP', ph: '(11) 90000-1112', em: 'priscila@modaprisma.exemplo', src: 'Meta · Vídeo Rebeca', owner: 'u3', life: 'Lead', score: 61, last: 'hoje 10:09' },
        { id: 'c13', nm: 'Henrique Batista', co: 'Batista Advocacia', seg: 'Advocacia', city: 'Ribeirão Preto/SP', ph: '(16) 90000-1113', em: 'henrique@batistaadv.exemplo', src: 'Indicação', owner: 'u2', life: 'Cliente diagnóstico', score: 81, last: 'ontem 09:40' },
        { id: 'c14', nm: 'Sabrina Duarte', co: 'Clínica Vitta Fisio', seg: 'Fisioterapia', city: 'Barueri/SP', ph: '(11) 90000-1114', em: 'sabrina@vittafisio.exemplo', src: 'Meta · Vídeo Rebeca', owner: 'u1', life: 'Cliente diagnóstico', score: 87, last: 'ontem 19:05' },
        { id: 'c15', nm: 'Diego Ramos', co: 'Ramos Auto Peças', seg: 'Autopeças', city: 'Diadema/SP', ph: '(11) 90000-1115', em: 'diego@ramosautopecas.exemplo', src: 'Prospector · Google Maps', owner: 'u3', life: 'Lead', score: 48, last: 'seg 14:10' },
        { id: 'c16', nm: 'Tatiane Moura', co: 'Doce Tati Confeitaria', seg: 'Confeitaria', city: 'Santo André/SP', ph: '(11) 90000-1116', em: 'tati@docetati.exemplo', src: 'Meta · Carrossel', owner: 'u2', life: 'Perdido', score: 35, last: '29/09' },
        { id: 'c17', nm: 'Otávio Pires', co: 'Pires Engenharia Solar', seg: 'Energia solar', city: 'Campinas/SP', ph: '(19) 90000-1117', em: 'otavio@piressolar.exemplo', src: 'Meta · Vídeo Rebeca', owner: 'u2', life: 'Cliente diagnóstico', score: 89, last: 'ontem 17:30' },
        { id: 'c18', nm: 'Natália Ribeiro', co: 'Studio N Beauty', seg: 'Salão de beleza', city: 'São Paulo/SP', ph: '(11) 90000-1118', em: 'natalia@studion.exemplo', src: 'Meta · Remarketing', owner: 'u3', life: 'Qualificado', score: 70, last: 'ontem 20:14' },
        { id: 'c19', nm: 'Leandro Souza', co: 'Souza Odontologia', seg: 'Odontologia', city: 'Guarulhos/SP', ph: '(11) 90000-1119', em: 'leandro@souzaodonto.exemplo', src: 'Prospector · Google Maps', owner: 'u3', life: 'Qualificado', score: 74, last: 'ter 15:02' },
        { id: 'c20', nm: 'Fernanda Lopes', co: 'Lopes Arquitetura', seg: 'Arquitetura', city: 'São Paulo/SP', ph: '(11) 90000-1120', em: 'fernanda@lopesarq.exemplo', src: 'Meta · Vídeo Rebeca', owner: 'u1', life: 'Cliente diagnóstico', score: 90, last: 'ontem 15:00' },
        { id: 'c21', nm: 'Rafael Martins', co: 'Martins Pneus', seg: 'Pneus e serviços', city: 'Osasco/SP', ph: '(11) 90000-1121', em: 'rafael@martinspneus.exemplo', src: 'Prospector · Google Maps', owner: 'u3', life: 'Lead', score: 41, last: 'hoje 07:50' },
        { id: 'c22', nm: 'Vanessa Cardoso', co: 'Escola Pequeno Saber', seg: 'Educação infantil', city: 'Sorocaba/SP', ph: '(15) 90000-1122', em: 'vanessa@pequenosaber.exemplo', src: 'Meta · Vídeo Rebeca', owner: 'u2', life: 'Cliente consultoria', score: 93, last: '30/09' },
        { id: 'c23', nm: 'Alexandre Teixeira', co: 'Teixeira Climatização', seg: 'Climatização', city: 'Santo André/SP', ph: '(11) 90000-1123', em: 'alexandre@teixeiraclima.exemplo', src: 'Meta · Estático', owner: 'u3', life: 'Lead', score: 25, last: 'hoje 10:22' },
        { id: 'c24', nm: 'Bianca Moreira', co: 'Clínica Derma Viva', seg: 'Dermatologia', city: 'São Caetano/SP', ph: '(11) 90000-1124', em: 'bianca@dermaviva.exemplo', src: 'Meta · Vídeo Rebeca', owner: 'u3', life: 'Qualificado', score: 80, last: 'ontem 16:45' },
      ],

      deals: [
        { id: 'd1', c: 'c11', p: 'inb', s: 'novo', v: 497, temp: 'frio', owner: 'u3', next: 'Cibelle está qualificando', age: 'agora' },
        { id: 'd2', c: 'c23', p: 'inb', s: 'novo', v: 497, temp: 'frio', owner: 'u3', next: 'Aguardando primeira resposta', age: '2 min' },
        { id: 'd3', c: 'c2', p: 'inb', s: 'conversa', v: 497, temp: 'morno', owner: 'u3', next: 'Revisar resposta sobre garantia', age: '43 min', flag: 'Revisão' },
        { id: 'd4', c: 'c12', p: 'inb', s: 'conversa', v: 497, temp: 'morno', owner: 'u3', next: 'Descobrir decisor', age: '22 min' },
        { id: 'd5', c: 'c4', p: 'inb', s: 'qualificado', v: 497, temp: 'quente', owner: 'u1', next: 'Ligar · pediu atendimento humano', age: '1 h', flag: 'Humano' },
        { id: 'd6', c: 'c18', p: 'inb', s: 'qualificado', v: 497, temp: 'morno', owner: 'u3', next: 'Enviar opções de horário', age: '14 h' },
        { id: 'd7', c: 'c10', p: 'inb', s: 'ofertado', v: 497, temp: 'quente', owner: 'u3', next: 'Pix enviado · lembrete às 12:30', age: '2 h' },
        { id: 'd8', c: 'c24', p: 'inb', s: 'ofertado', v: 497, temp: 'morno', owner: 'u3', next: 'Follow-up D+1 com caso parecido', age: '18 h' },
        { id: 'd9', c: 'c1', p: 'inb', s: 'pago', v: 497, temp: 'quente', owner: 'u1', next: 'Diagnóstico sex 09/10 · 10:00', age: '1 dia' },
        { id: 'd10', c: 'c14', p: 'inb', s: 'pago', v: 497, temp: 'quente', owner: 'u1', next: 'Diagnóstico amanhã · 09:00', age: '1 dia' },
        { id: 'd11', c: 'c20', p: 'inb', s: 'realizado', v: 497, temp: 'quente', owner: 'u1', next: 'Atribuir handoff ao Caio', age: '1 dia', flag: 'Handoff' },

        { id: 'd12', c: 'c3', p: 'cons', s: 'handoff', v: 9800, temp: 'quente', owner: 'u2', next: 'Reunião sex 16:00 com o sócio', age: '1 dia' },
        { id: 'd13', c: 'c13', p: 'cons', s: 'handoff', v: 12000, temp: 'morno', owner: 'u2', next: 'Primeiro contato do Caio', age: '1 dia' },
        { id: 'd14', c: 'c7', p: 'cons', s: 'reuniao', v: 12000, temp: 'quente', owner: 'u2', next: 'Reunião hoje · 14:00', age: '3 dias' },
        { id: 'd15', c: 'c5', p: 'cons', s: 'proposta', v: 14500, temp: 'morno', owner: 'u2', next: 'Follow-up D+2 hoje · 11:00', age: '2 dias' },
        { id: 'd16', c: 'c17', p: 'cons', s: 'proposta', v: 16800, temp: 'quente', owner: 'u2', next: 'Proposta enviada ontem', age: '1 dia' },
        { id: 'd17', c: 'c6', p: 'cons', s: 'negociacao', v: 9800, temp: 'quente', owner: 'u2', next: 'Pediu parcelar em 4x', age: '5 dias' },
        { id: 'd18', c: 'c8', p: 'cons', s: 'ganho', v: 9800, temp: 'quente', owner: 'u2', next: 'Contrato assinado em 06/10', age: '1 dia' },
        { id: 'd19', c: 'c16', p: 'cons', s: 'perdido', v: 8600, temp: 'frio', owner: 'u2', next: 'Motivo: sem verba no momento', age: '8 dias' },

        { id: 'd20', c: 'c21', p: 'out', s: 'importado', v: 497, temp: 'frio', owner: 'u3', next: 'Toque 1 amanhã · 08:30', age: 'hoje' },
        { id: 'd21', c: 'c15', p: 'out', s: 'cadencia', v: 497, temp: 'frio', owner: 'u3', next: 'Toque 4 de 8 · avaliação real', age: '4 dias' },
        { id: 'd22', c: 'c9', p: 'out', s: 'respondeu', v: 497, temp: 'morno', owner: 'u3', next: 'Perguntou o preço · responder', age: '26 min', flag: 'Responder' },
        { id: 'd23', c: 'c19', p: 'out', s: 'reuniao', v: 497, temp: 'quente', owner: 'u3', next: 'Diagnóstico qui 08/10 · 17:00', age: '1 dia' },
      ],

      instances: [
        { id: 'i1', nm: 'Comercial Lothem', type: 'oficial', num: '+55 11 4000-0000', st: 'on', quality: 'Alta', tier: '1.000 conversas iniciadas / 24 h', today: 412, agents: ['ia', 'u3', 'u1'], use: 'Entrada dos anúncios do Meta. A Cibelle atende primeiro.' },
        { id: 'i2', nm: 'Prospecção · Marina', type: 'naooficial', num: '+55 11 90000-0103', st: 'on', quality: '—', tier: 'Limite seguro: 40 novas conversas / dia', today: 38, agents: ['u3'], use: 'Cadência outbound dos leads do Prospector.' },
        { id: 'i3', nm: 'Closer · Caio', type: 'naooficial', num: '+55 11 90000-0102', st: 'off', quality: '—', tier: 'Limite seguro: 40 novas conversas / dia', today: 0, agents: ['u2'], use: 'Relacionamento depois do handoff.' },
      ],
      templates: [
        { nm: 'lembrete_diagnostico_24h', cat: 'Utilidade', st: 'Aprovado', lang: 'pt_BR', body: 'Oi, {{1}}! Passando para lembrar do seu diagnóstico amanhã às {{2}} com a Rebeca. O link da chamada é este: {{3}}' },
        { nm: 'confirmacao_pagamento', cat: 'Utilidade', st: 'Aprovado', lang: 'pt_BR', body: 'Pagamento recebido, {{1}}. Seu diagnóstico está confirmado para {{2}}.' },
        { nm: 'retomar_conversa', cat: 'Marketing', st: 'Aprovado', lang: 'pt_BR', body: 'Oi, {{1}}! Aqui é a Cibelle, da Lothem. Ficou alguma dúvida sobre o diagnóstico que conversamos?' },
        { nm: 'reativacao_15d', cat: 'Marketing', st: 'Em análise', lang: 'pt_BR', body: 'Oi, {{1}}. Abrimos 3 horários de diagnóstico na próxima semana. Quer que eu reserve um pra você?' },
        { nm: 'pesquisa_satisfacao', cat: 'Marketing', st: 'Rejeitado', lang: 'pt_BR', body: 'De 1 a 5, quanto você recomendaria a Lothem? Responda e ganhe um bônus.', why: 'Oferta de bônus em troca de avaliação' },
      ],
      integrations: [
        { lg: 'M', nm: 'Meta Lead Ads', d: 'Leads de formulário e clique para WhatsApp entram no funil Inbound.', st: 'on' },
        { lg: 'C', nm: 'Meta · API de Conversões', d: 'Devolve à Meta os eventos Lead qualificado, Diagnóstico pago e Consultoria fechada.', st: 'on' },
        { lg: 'G', nm: 'Google Agenda', d: 'Diagnósticos e reuniões viram eventos com link de chamada.', st: 'on' },
        { lg: 'P', nm: 'Pagamentos · Pix e cartão', d: 'Gera o link do diagnóstico e confirma o pagamento sozinho.', st: 'on' },
        { lg: 'S', nm: 'Prospector (Google Maps)', d: 'Importa o CSV do Prospector direto no funil Outbound.', st: 'on' },
        { lg: 'W', nm: 'Webhooks', d: 'Envia eventos do CRM para outras ferramentas.', st: 'off' },
      ],

      conversations: [
        { id: 'cv6', c: 'c11', inst: 'i1', st: 'ia', unread: 0, t: '10:19', q: {}, conf: 92, msgs: [
          { f: 'lead', x: 'Olá, gostaria de mais informações', t: '10:19' },
          { f: 'ia', x: 'Olá, Bruno! Aqui é a Cibelle, da Lothem. Que bom que você chamou.', t: '10:19' },
          { f: 'ia', x: 'Me conta: qual é o seu negócio?', t: '10:19' },
        ] },
        { id: 'cv7', c: 'c4', inst: 'i1', st: 'espera', unread: 1, t: '10:16', slaType: 'transfer', slaSince: '10:16', conf: 74, q: { dor: 'Academia cheia de manhã e vazia à tarde; quer vender plano para o horário ocioso.', decisor: 'Ela decide sozinha.', momento: 'Agora, antes do verão.', capacidade: 'Investe R$ 800/mês em impulsionamento.' }, msgs: [
          { f: 'sys', x: 'Lead do anúncio "[CAPT] Estático · Checklist do empresário"', t: '09:20' },
          { f: 'lead', x: 'Oi, vi o anúncio do checklist', t: '09:20' },
          { f: 'ia', x: 'Oi, Juliana! Aqui é a Cibelle, da Lothem. Que bom que você chamou.', t: '09:20' },
          { f: 'ia', x: 'O que te chamou atenção no checklist?', t: '09:21' },
          { f: 'lead', x: 'Tenho uma academia em Osasco. De manhã lota, à tarde fica às moscas', t: '09:26' },
          { f: 'ia', x: 'Entendi. E vocês já tentaram vender algum plano específico pro horário da tarde?', t: '09:26' },
          { f: 'lead', x: 'Já fiz promoção, impulsiono uns 800 por mês, mas não muda muito', t: '09:40' },
          { f: 'ia', x: 'Faz sentido. Se a gente conseguisse resolver isso, seria pra agora ou mais pra frente?', t: '09:41' },
          { f: 'lead', x: 'Agora né, antes do verão', t: '10:02' },
          { f: 'lead', x: 'Prefiro falar com uma pessoa, pode ser?', t: '10:16' },
          { f: 'ia', x: 'Claro, Juliana. Vou chamar alguém do time agora.\nJá deixei anotado tudo o que você me contou, pra você não precisar repetir.', t: '10:16' },
          { f: 'sys', x: 'Transferida para humano · SLA de transferência começou a contar', t: '10:16', cls: 'bad' },
        ] },
        { id: 'cv2', c: 'c12', inst: 'i1', st: 'ia', unread: 0, t: '10:09', conf: 89, q: { dor: 'Site tem visita, mas converte 0,4%.' }, msgs: [
          { f: 'sys', x: 'Lead do anúncio "[CAPT] Diagnóstico · Vídeo Rebeca 45s"', t: '10:02' },
          { f: 'lead', x: 'Oi, quero saber do diagnóstico', t: '10:02' },
          { f: 'ia', x: 'Oi, Priscila! Aqui é a Cibelle, da Lothem 🙂', t: '10:02' },
          { f: 'ia', x: 'Antes de te explicar, me conta um pouco da sua empresa?', t: '10:02' },
          { f: 'lead', x: 'Tenho um e-commerce de moda feminina, vendo pelo site e pelo Instagram', t: '10:05' },
          { f: 'ia', x: 'Que legal. E hoje, o que mais pega nas vendas? Visita no site, conversão ou recompra?', t: '10:05' },
          { f: 'lead', x: 'O site tem visita mas quase ninguém compra. A conversão tá em 0,4%', t: '10:09' },
          { f: 'ia', x: 'Esse número diz bastante. Normalmente o problema está entre o anúncio e o checkout.', t: '10:09' },
          { f: 'ia', x: 'Você toca a loja sozinha ou tem sócio?', t: '10:09' },
        ] },
        { id: 'cv1', c: 'c2', inst: 'i1', st: 'ia', unread: 0, t: '09:53', conf: 58, flag: true, q: { dor: 'Movimento caiu; Instagram não vende; depende de indicação e arquiteto.', capacidade: 'Já investiu R$ 4 mil com agência, sem retorno.' }, msgs: [
          { f: 'sys', x: 'Lead do anúncio "[CAPT] Carrossel · Post todo dia e nada de cliente"', t: '09:41' },
          { f: 'lead', x: 'Bom dia, vi o anúncio de vocês', t: '09:41' },
          { f: 'ia', x: 'Bom dia, Rodrigo! Aqui é a Cibelle, da Lothem.', t: '09:41' },
          { f: 'ia', x: 'Me conta: o que te chamou atenção no anúncio?', t: '09:41' },
          { f: 'lead', x: 'Tenho uma loja de móveis planejados em Guarulhos. O movimento caiu muito esse ano', t: '09:44' },
          { f: 'ia', x: 'Puxa, entendo. Hoje o cliente novo chega mais por indicação, Instagram ou loja?', t: '09:44' },
          { f: 'lead', x: 'Indicação e arquiteto parceiro. Instagram a gente posta mas não vende', t: '09:47' },
          { f: 'ia', x: 'Faz sentido. Planejado tem ticket alto, então cada cliente que não chega pesa bastante.', t: '09:47' },
          { f: 'ia', x: 'Vocês já investiram em anúncio pago alguma vez?', t: '09:47' },
          { f: 'lead', x: 'Já, com uma agência. Gastei 4 mil e não veio nada', t: '09:52' },
          { f: 'lead', x: 'Vocês garantem quantos clientes por mês?', t: '09:52' },
          { f: 'ia', x: 'Entendo a frustração, Rodrigo. A gente não trabalha com garantia de número de clientes, porque isso depende de vários fatores do negócio.', t: '09:53' },
          { f: 'ia', x: 'O que fazemos é um diagnóstico para entender onde está o gargalo antes de investir de novo. Quer que eu te explique como funciona?', t: '09:53' },
          { f: 'sys', x: 'Resposta enviada para revisão · confiança 58%', t: '09:53', cls: 'warn' },
        ] },
        { id: 'cv8', c: 'c9', inst: 'i2', st: 'humano', who: 'u3', unread: 2, t: '09:58', slaType: 'retorno', slaSince: '09:58', conf: 0, q: { dor: 'Nota 4,8 no Google e nenhum site.' }, msgs: [
          { f: 'sys', x: 'Cadência outbound · toque 1 de 8', t: '08:05' },
          { f: 'user', u: 'u3', x: 'Oi, Gustavo, tudo bem? Aqui é a Marina, da Lothem.', t: '08:05' },
          { f: 'user', u: 'u3', x: 'Vi que a Oficina Almeida tem 4,8 no Google com 212 avaliações, e não achei um site de vocês.\nMontei uma prévia com as fotos daí. Faz sentido eu te mandar o link?', t: '08:05' },
          { f: 'lead', x: 'Pode mandar', t: '09:58' },
          { f: 'lead', x: 'Quanto fica isso?', t: '09:58' },
        ] },
        { id: 'cv3', c: 'c10', inst: 'i1', st: 'aguardando', unread: 0, t: '08:31', conf: 93, q: { dor: 'Agenda de banho cheia só no sábado; semana parada.', decisor: 'Renata e o marido.', momento: 'Este mês.', capacidade: 'Paga R$ 250/mês para um freelancer postar.' }, msgs: [
          { f: 'lead', x: 'Pode ser sexta às 11h?', t: '08:28' },
          { f: 'ia', x: 'Pode sim! Sexta, 09/10, às 11h com a Rebeca.', t: '08:30' },
          { f: 'ia', x: 'Prontinho, Renata. O link do Pix está aqui embaixo. Assim que o pagamento cair, eu confirmo o horário.', t: '08:31', pay: true },
          { f: 'sys', x: 'Lembrete automático programado para 12:30', t: '08:31' },
        ] },
        { id: 'cv4', c: 'c1', inst: 'i1', st: 'humano', who: 'u1', unread: 0, t: '08:26', conf: 95, q: { dor: 'Agenda com buracos na terça e quarta; paciente novo só por convênio.', decisor: 'Ana (sócia única).', momento: 'Agora.', capacidade: 'Investe R$ 1.200/mês em anúncio.' }, msgs: [
          { f: 'sys', x: 'Pagamento confirmado · R$ 497 via Pix · ontem 17:20', t: '17:20', cls: 'ok' },
          { f: 'ia', x: 'Pagamento recebido, Ana! Seu diagnóstico ficou para sexta, 09/10, às 10h, com a Rebeca.', t: '17:21' },
          { f: 'lead', x: 'Perfeito! Preciso levar alguma coisa?', t: '08:12' },
          { f: 'note', u: 'u1', x: '@Marina pede o acesso ao Instagram e ao gerenciador de anúncios dela antes de sexta.', t: '08:18' },
          { f: 'user', u: 'u1', x: 'Oi, Ana! Aqui é a Rebeca.\nSe puder, me manda antes de sexta: quanto a clínica fatura por mês e quantos pacientes novos chegam. Pode ser número aproximado.', t: '08:20' },
          { f: 'lead', x: 'Claro, mando hoje à tarde', t: '08:26' },
        ] },
        { id: 'cv5', c: 'c3', inst: 'i1', st: 'humano', who: 'u2', unread: 0, t: '09:33', conf: 0, q: { dor: 'Escritório depende de indicação; quer 15 clientes PJ novos até março.', decisor: 'Felipe e o sócio, Prado.', momento: 'Agora, antes do fechamento do ano.', capacidade: 'Orçamento aprovado para consultoria trimestral.' }, msgs: [
          { f: 'sys', x: 'Handoff · Cibelle → Caio Duarte · diagnóstico realizado em 06/10', t: '09:05', cls: 'gold' },
          { f: 'user', u: 'u2', x: 'Felipe, bom dia! Sou o Caio, trabalho com a Rebeca. Ela me passou o resumo do diagnóstico de ontem.', t: '09:10' },
          { f: 'user', u: 'u2', x: 'Separei 30 min pra te mostrar como o plano fica na prática. Quinta 11h ou sexta 16h, qual fica melhor?', t: '09:10' },
          { f: 'lead', x: 'Sexta 16h. Meu sócio vai junto', t: '09:31' },
          { f: 'user', u: 'u2', x: 'Ótimo, é bom ele estar. Mando o convite agora.', t: '09:33' },
        ] },
        { id: 'cv9', c: 'c16', inst: 'i1', st: 'encerrada', unread: 0, t: '29/09', conf: 0, q: { dor: 'Vendas caem fora de datas comemorativas.', capacidade: 'Sem verba no momento.' }, msgs: [
          { f: 'user', u: 'u2', x: 'Tati, vou deduzir que não é prioridade agora e encerro por aqui. Se mudar, é só me chamar.', t: '29/09' },
          { f: 'lead', x: 'Obrigada, Caio. Em janeiro eu te chamo', t: '29/09' },
          { f: 'sys', x: 'Conversa encerrada · lembrete de reativação em 15/01', t: '29/09' },
        ] },
      ],

      tasks: [
        { id: 't6', t: 'Enviar resumo do diagnóstico para Fernanda Lopes', type: 'Mail', who: 'u1', due: -1, at: '18:00', deal: 'd11', pri: 'alta', xp: 10 },
        { id: 't7', t: 'Reconectar a instância "Closer · Caio" pelo QR Code', type: 'QrCode', who: 'u2', due: -1, at: '12:00', pri: 'alta', xp: 10, go: 'canais' },
        { id: 't8', t: 'Responder Gustavo (Oficina Almeida): perguntou o preço', type: 'MessageCircle', who: 'u3', due: 0, at: '10:00', deal: 'd22', pri: 'alta', xp: 10 },
        { id: 't1', t: 'Ligar para Juliana Torres: pediu atendimento humano', type: 'Phone', who: 'u1', due: 0, at: '10:30', deal: 'd5', pri: 'alta', xp: 10 },
        { id: 't4', t: 'Follow-up D+2 da proposta da Vieira Construtora', type: 'Repeat', who: 'u2', due: 0, at: '11:00', deal: 'd15', pri: 'média', xp: 10 },
        { id: 't5', t: 'Revisar as 6 respostas da Cibelle marcadas para revisão', type: 'GraduationCap', who: 'u1', due: 0, at: '12:00', pri: 'média', xp: 10, go: 'sdr' },
        { id: 't3', t: 'Reunião de consultoria · Nogueira Imóveis', type: 'Video', who: 'u2', due: 0, at: '14:00', deal: 'd14', pri: 'alta', xp: 10 },
        { id: 't2', t: 'Preparar o diagnóstico da Sabrina (Vitta Fisio)', type: 'ClipboardList', who: 'u1', due: 0, at: '16:00', deal: 'd10', pri: 'média', xp: 10 },
        { id: 't9', t: 'Diagnóstico · Sabrina Duarte (Vitta Fisio)', type: 'Video', who: 'u1', due: 1, at: '09:00', deal: 'd10', pri: 'alta', xp: 10 },
        { id: 't12', t: 'Aprovar os 2 criativos novos do vídeo da Rebeca', type: 'Megaphone', who: 'u4', due: 1, at: '11:00', pri: 'média', xp: 10 },
        { id: 't15', t: 'Diagnóstico · Leandro Souza (Souza Odontologia)', type: 'Video', who: 'u1', due: 1, at: '17:00', deal: 'd23', pri: 'média', xp: 10 },
        { id: 't10', t: 'Diagnóstico · Ana Beatriz (Sorriso Pleno)', type: 'Video', who: 'u1', due: 2, at: '10:00', deal: 'd9', pri: 'alta', xp: 10 },
        { id: 't13', t: 'Diagnóstico · Renata (Pet Feliz), se o Pix cair', type: 'Video', who: 'u1', due: 2, at: '11:00', deal: 'd7', pri: 'média', xp: 10 },
        { id: 't11', t: 'Reunião · Felipe Costa e sócio', type: 'Video', who: 'u2', due: 2, at: '16:00', deal: 'd12', pri: 'alta', xp: 10 },
        { id: 't14', t: 'Atualizar a oferta do diagnóstico na base da Cibelle (92 dias sem revisão)', type: 'BookOpen', who: 'u1', due: 5, at: '09:00', pri: 'média', xp: 10, go: 'sdr' },
        { id: 't16', t: 'Diagnóstico · Fernanda Lopes (Lopes Arquitetura)', type: 'Video', who: 'u1', due: -1, at: '14:00', deal: 'd11', pri: 'alta', xp: 10, done: true },
        { id: 't17', t: 'Enviar proposta da Pires Engenharia Solar', type: 'FileText', who: 'u2', due: -1, at: '17:00', deal: 'd16', pri: 'alta', xp: 10, done: true },
      ],

      channels: [
        { id: 'geral', nm: 'geral', unread: 0, msgs: [
          { day: 'Ontem' },
          { u: 'u1', t: '18:40', x: 'Fechamos a Fontes Idiomas! Primeira consultoria de outubro. Valeu, @Caio.', react: '🔥 4' },
          { u: 'u2', t: '18:52', x: 'A conta de valor fez a diferença. Ela viu quanto perdia por turma vazia e decidiu na hora.' },
          { day: 'Hoje' },
          { u: 'u1', t: '08:02', x: 'Bom dia, time. Hoje: reunião da Nogueira às 14h e a fila de revisão da Cibelle. Amanhã cedo tem diagnóstico da Vitta Fisio.' },
        ] },
        { id: 'comercial', nm: 'comercial', unread: 2, msgs: [
          { day: 'Hoje' },
          { u: 'u4', t: '08:47', x: 'Subi 2 variações novas do vídeo da Rebeca. CPL de ontem no conjunto Empresários 30–55: R$ 22,40.' },
          { u: 'u3', t: '09:15', x: 'A Cibelle está segurando bem objeção de tempo. Preço ainda escorrega. @Rebeca dá pra treinar mais essa semana?' },
          { u: 'u1', t: '09:20', x: 'Dá. Entrei no desafio "Objeção de preço". Vou corrigir as respostas da fila hoje.', react: '👍 2' },
        ] },
        { id: 'handoff', nm: 'handoff-closer', unread: 1, msgs: [
          { day: 'Ontem' },
          { u: 'ia', t: '15:42', x: 'Handoff pronto para @Caio.', deal: 'd12', sum: [['Dor', 'Escritório depende de indicação. Quer 15 clientes PJ novos até março.'], ['Decisor', 'Felipe e o sócio, Prado. Os dois precisam estar na reunião.'], ['Diagnóstico', 'Site sem página de serviços e Google Meu Negócio desatualizado.'], ['Próximo passo', 'Reunião com os dois sócios, ainda esta semana.']] },
          { u: 'u2', t: '15:58', x: 'Peguei. Já chamei o Felipe.' },
          { day: 'Hoje' },
          { u: 'ia', t: '08:40', x: 'Handoff de Fernanda Lopes preparado. Falta atribuir um closer.', deal: 'd11', sum: [['Dor', 'Projetos de alto padrão chegam só por indicação de construtora.'], ['Decisor', 'Fernanda decide sozinha.'], ['Diagnóstico', 'Instagram com portfólio forte, mas sem chamada para orçamento.'], ['Próximo passo', 'Apresentar o plano de 90 dias com foco em captação direta.']], pending: true },
        ] },
        { id: 'treino', nm: 'treinamento-ia', unread: 0, msgs: [
          { day: 'Segunda' },
          { u: 'ia', t: '17:10', x: 'Aprendi 3 respostas novas aprovadas pela @Rebeca: "já tenho agência", "manda por aqui" e "sem tempo agora".' },
          { u: 'u3', t: '17:22', x: 'A de "manda por aqui" ficou ótima. Já vi a Cibelle usando hoje.' },
          { day: 'Hoje' },
          { u: 'ia', t: '09:53', x: 'Marquei para revisão uma pergunta sobre garantia de resultado (Rodrigo Menezes). Confiança 58%.' },
        ] },
      ],
      dms: [
        { id: 'dm-u2', u: 'u2', unread: 0, msgs: [{ day: 'Hoje' }, { u: 'u2', t: '09:40', x: 'Rebeca, a Camila pediu para parcelar em 4x. Posso oferecer se ela fechar até sexta?' }] },
        { id: 'dm-u3', u: 'u3', unread: 1, msgs: [{ day: 'Hoje' }, { u: 'u3', t: '10:17', x: 'A Juliana pediu humano. Você liga ou eu ligo?' }] },
        { id: 'dm-u4', u: 'u4', unread: 0, msgs: [{ day: 'Ontem' }, { u: 'u4', t: '17:02', x: 'Vou pausar o estático do checklist se o CPL passar de R$ 40 de novo.' }] },
      ],

      kb: [
        { id: 'k1', ic: 'FileText', nm: 'Playbook SDR Lothem v3', type: 'PDF · 24 páginas', cat: 'Treinamento', st: 'ok', uses: 1284, upd: '12/09' },
        { id: 'k2', ic: 'ListChecks', nm: 'Roteiro de qualificação: dor, decisor, momento e capacidade', type: 'Documento', cat: 'Playbook', st: 'ok', uses: 2210, upd: '20/09' },
        { id: 'k3', ic: 'Tag', nm: 'Oferta: Diagnóstico Estratégico de Marketing', type: 'Documento', cat: 'Oferta', st: 'old', uses: 846, upd: '07/07', warn: '92 dias sem revisão' },
        { id: 'k4', ic: 'Table', nm: 'Objeções frequentes e respostas aprovadas', type: 'Planilha · 38 objeções', cat: 'Objeções', st: 'ok', uses: 731, upd: '05/10' },
        { id: 'k5', ic: 'Newspaper', nm: 'Artigo: Por que postar todo dia não traz cliente', type: 'Artigo do blog', cat: 'Artigo', st: 'ok', uses: 188, upd: '18/09' },
        { id: 'k6', ic: 'Newspaper', nm: 'Artigo: Custo por cliente para quem não usa planilha', type: 'Artigo do blog', cat: 'Artigo', st: 'ok', uses: 97, upd: '25/09' },
        { id: 'k7', ic: 'FileAudio', nm: 'Áudio: treinamento de abordagem com a Rebeca', type: 'Áudio · 42 min · transcrito', cat: 'Treinamento', st: 'ok', uses: 402, upd: '01/10' },
        { id: 'k8', ic: 'FileVideo', nm: 'Vídeo: como a Rebeca conduz o diagnóstico', type: 'Vídeo · 18 min · transcrito', cat: 'Treinamento', st: 'ok', uses: 265, upd: '01/10' },
        { id: 'k9', ic: 'CircleHelp', nm: 'Perguntas frequentes: pagamento, reembolso e remarcação', type: 'Documento', cat: 'FAQ', st: 'ok', uses: 512, upd: '28/09' },
        { id: 'k10', ic: 'BadgeCheck', nm: 'Casos que a Cibelle pode citar', type: 'Documento · 3 casos', cat: 'Prova', st: 'pend', uses: 0, upd: '06/10', warn: 'Aguardando sua validação' },
      ],
      skills: [
        { nm: 'Abertura', v: 94 }, { nm: 'Qualificação', v: 88 }, { nm: 'Oferta do diagnóstico', v: 82 }, { nm: 'Agendamento', v: 95 },
        { nm: 'Pós-pagamento', v: 90 }, { nm: 'Objeção de preço', v: 61 }, { nm: 'Objeção de momento', v: 77 }, { nm: 'Fora do escopo', v: 58 },
      ],
      iaStats: { convs: 238, qual: '40,3%', sold: 38, soloSold: 29, transfers: 24, conf: 87, csat: '4,7', approvals: 52 },
      reviews: [
        { id: 'r1', who: 'Rodrigo Menezes', co: 'Menezes Móveis', q: 'Vocês garantem quantos clientes por mês?', a: 'Entendo a frustração, Rodrigo. A gente não trabalha com garantia de número de clientes, porque isso depende de vários fatores do negócio.', conf: 58, why: 'Tema sensível: promessa de resultado', skill: 'Objeção de preço', sent: true,
          ideal: 'Número de cliente eu não garanto, Rodrigo. E desconfia de quem garante.\nO que dá pra garantir é o processo: no diagnóstico a Rebeca mostra onde os R$ 4 mil se perderam e o que muda daqui pra frente.\nQuer que eu te explique como funciona?' },
        { id: 'r2', who: 'Bianca Moreira', co: 'Clínica Derma Viva', q: 'Quanto custa a consultoria depois?', a: 'A consultoria começa em R$ 6.000 por mês, mas o valor exato a Rebeca te passa no diagnóstico.', conf: 52, why: 'Preço da consultoria não está cadastrado. A resposta foi retida e não chegou ao lead.', skill: 'Objeção de preço', sent: false, blocked: true,
          ideal: 'Depende do que o diagnóstico mostrar, Bianca. Tem cliente que precisa de 3 meses, tem cliente que precisa de 6.\nNo diagnóstico a Rebeca te passa o valor certo pro seu caso, e os R$ 497 são abatidos se vocês seguirem.' },
        { id: 'r3', who: 'Natália Ribeiro', co: 'Studio N Beauty', q: 'Dá pra parcelar o diagnóstico?', a: 'O diagnóstico é R$ 497 à vista no Pix.', conf: 63, why: 'Forma de pagamento desatualizada na base', skill: 'Oferta do diagnóstico', sent: true,
          ideal: 'Dá sim, Natália. No cartão sai em até 3x sem juros. No Pix é à vista.\nQual fica melhor pra você?' },
        { id: 'r4', who: 'Alexandre Teixeira', co: 'Teixeira Climatização', q: 'Vocês atendem empresa fora de São Paulo?', a: 'Acredito que sim, mas vou confirmar com a equipe.', conf: 46, why: 'Informação ausente na base', skill: 'Fora do escopo', sent: true,
          ideal: 'Atendemos sim. O diagnóstico e a consultoria são por videochamada, então a cidade não muda nada.' },
        { id: 'r5', who: 'Priscila Antunes', co: 'Moda Prisma', q: 'Já tenho uma agência, por que eu trocaria?', a: 'A Lothem tem uma abordagem diferente, focada em resultado e inteligência aplicada ao marketing.', conf: 66, why: 'Resposta genérica, sem pergunta de volta', skill: 'Objeção de preço', sent: true,
          ideal: 'Não precisa trocar pra fazer o diagnóstico. Muita gente faz justamente pra ter uma segunda opinião sobre o que a agência entrega.\nHoje você sente que está faltando o quê no trabalho deles?' },
        { id: 'r6', who: 'Bruno Carvalho', co: 'Carvalho Burger', q: 'Vocês fazem cardápio e site também?', a: 'Fazemos sim! Criamos sites, cardápios, identidade visual e muito mais.', conf: 68, why: 'Serviço fora da oferta principal', skill: 'Fora do escopo', sent: true,
          ideal: 'Site faz parte de alguns planos, cardápio não é com a gente.\nAntes de pensar em peça, me conta: hoje o que mais trava as vendas da hamburgueria?' },
      ],
      rules: [
        { on: true, t: 'Nunca prometer resultado em número', d: 'Nada de "vai trazer X clientes". A Cibelle promete processo e entregáveis.', lock: true },
        { on: true, t: 'Só informar preço que está cadastrado na oferta', d: 'Pergunta sobre preço não cadastrado é retida e vai para revisão.', lock: true },
        { on: true, t: 'Dizer que é assistente virtual quando perguntarem', d: 'A Cibelle não finge ser pessoa.', lock: true },
        { on: true, t: 'Não pedir documento pessoal ou dado bancário', d: 'LGPD. Dados sensíveis só por canal definido pela equipe.', lock: true },
        { on: true, t: 'Respeitar pedido para não ser contatado', d: 'Marca o contato como "não contatar" e encerra na hora.', lock: true },
        { on: true, t: 'Uma ideia e uma pergunta por mensagem', d: 'Mensagens curtas, em blocos, como gente digita no WhatsApp.' },
        { on: true, t: 'Emoji com moderação', d: 'No máximo um por conversa, e só na abertura.' },
        { on: false, t: 'Atender fora do horário comercial sem avisar', d: 'Desligado: fora do horário, a Cibelle avisa que alguém do time responde temas sensíveis no dia seguinte.' },
      ],
      handoffRules: [
        'O lead pede para falar com uma pessoa',
        'A confiança da resposta fica abaixo de 70%',
        'Irritação, reclamação ou assunto jurídico',
        'Diagnóstico pago: prepara o resumo e chama o Closer',
      ],
    },

    /* ======================= LOTHEM — CRÉDITO ======================= */
    cred: {
      id: 'cred', name: 'LOTHEM — Inteligência em Crédito · PJ', short: 'Lothem Crédito PJ', mark: 'PJ', hue: 'gold',
      plan: 'Profissional', members: ['u1', 'u3'],
      sla: { primeira: 10, transfer: 15, retorno: 30, followup: 48, warnAt: 75, business: true, notifyBoss: true, redistribute: false, iaHold: false, roles: ['SDR'] },
      autofill: {
        on: false, minConf: 90,
        fields: [
          { k: 'cadastro', nm: 'Cadastro do contato', d: 'Empresa, segmento, cidade e e-mail.', on: true },
          { k: 'qualif', nm: 'Necessidade de crédito', d: 'Para que é o dinheiro, prazo e quem decide.', on: true },
          { k: 'score', nm: 'Pontuação', d: 'Recalcula a cada resposta.', on: false },
          { k: 'etapa', nm: 'Etapa do funil', d: 'Move o negócio quando a conversa avança.', on: false },
          { k: 'task', nm: 'Tarefas e agenda', d: 'Cria a reunião combinada.', on: true },
        ],
        never: ['CPF, RG e fotos de documentos', 'Dados bancários', 'Taxa, prazo ou limite de crédito'],
        stats: { today: 0, corrected: 0 },
        log: [],
      },
      slaStats: [
        { u: 'u3', convs: 58, inSla: 91, avg: '8 min 20 s', breaches: 5 },
        { u: 'u1', convs: 33, inSla: 96, avg: '5 min 02 s', breaches: 1 },
      ],
      ia: { name: 'Cibelle', role: 'Assistente de crédito IA', mode: 'cop', offer: 'Análise de perfil de crédito PJ', price: 0 },
      route: {
        cpl: 22.7, outbound: 40, rateNote: 'Taxas dos últimos 30 dias · volume médio por contrato R$ 92.500 (fictício)',
        steps: [
          { k: 'contatos', nm: 'Contatos novos', ic: 'UserPlus', who: ['ia', 'u3'], mtd: 34, r: 0.52, verb: 'explicam a necessidade' },
          { k: 'necessidade', nm: 'Necessidade entendida', ic: 'ListChecks', who: ['u3'], mtd: 18, r: 0.53, verb: 'mandam o perfil' },
          { k: 'perfil', nm: 'Perfis analisados', one: 'perfil analisado', ic: 'ShieldCheck', who: ['u1'], mtd: 12, r: 0.45, verb: 'recebem proposta' },
          { k: 'proposta', nm: 'Propostas enviadas', ic: 'FileText', who: ['u1'], mtd: 5, r: 0.43, verb: 'assinam o contrato' },
          { k: 'contratado', nm: 'Contratos fechados', one: 'contrato fechado', ic: 'BadgeCheck', who: ['u1'], mtd: 2, value: 92500 },
        ],
        sdr: 'u3', closer: 'u1', sdrStep: 'necessidade', closerStep: 'contratado', closerPrep: 'proposta',
      },
      metrics: {
        goalLabel: 'Volume contratado em outubro', goal: 900000, done: 185000, money: true,
        kpis: [
          { k: 'Contatos novos', v: '34', sub: 'no mês', delta: 6, spark: [4, 5, 6, 4, 5, 6, 4], go: 'contatos', hint: 'Meta e indicação' },
          { k: 'Perfis analisados', v: '12', delta: 2, spark: [1, 2, 2, 1, 2, 2, 2], go: 'funis', hint: 'taxa 35%' },
          { k: 'Propostas enviadas', v: '5', delta: 1, spark: [0, 1, 1, 0, 1, 1, 1], go: 'funis', hint: 'R$ 640 mil' },
          { k: 'Contratos fechados', v: '2', delta: 0, spark: [0, 0, 1, 0, 0, 1, 0], go: 'funis', hint: 'R$ 185 mil' },
          { k: 'Primeira resposta', v: '2', unit: 'min', delta: 5, spark: [5, 4, 4, 3, 3, 2, 2], go: 'sdr', hint: 'Cibelle no modo copiloto', invert: true },
          { k: 'Satisfação', v: '4,8', delta: 1, spark: [4.6, 4.7, 4.7, 4.8, 4.8, 4.8, 4.8], go: 'suporte', hint: '21 respostas' },
        ],
        funnel: [
          { nm: 'Contatos novos', v: 112 }, { nm: 'Necessidade entendida', v: 58 }, { nm: 'Perfil analisado', v: 31 }, { nm: 'Proposta enviada', v: 14 }, { nm: 'Contratado', v: 6, gold: true },
        ],
        funnelNote: 'Últimos 30 dias · sem promessa de aprovação, taxa ou prazo',
        series: { a: [3, 4, 2, 5, 4, 3, 2, 4, 5, 3, 4, 3, 2, 5, 4, 4, 3, 5, 4, 3, 5, 4, 3, 4, 5, 6, 4, 5, 6, 4], b: [1, 2, 1, 3, 2, 1, 1, 2, 3, 1, 2, 2, 1, 3, 2, 2, 2, 3, 2, 1, 3, 2, 2, 2, 3, 3, 2, 3, 3, 2], la: 'Contatos', lb: 'Necessidade entendida', start: [8, 9] },
        campaigns: [
          { nm: '[CAPT] Capital de giro · Vídeo', inv: 1450, leads: 64, q: 31, d: 8, c: 3 },
          { nm: '[CAPT] Antecipação de recebíveis · Carrossel', inv: 980, leads: 48, q: 27, d: 6, c: 3 },
        ],
        campaignCols: ['Necessidade', 'Propostas', 'Contratos'],
        insight: 'Antecipação de recebíveis tem contato mais barato e a mesma taxa de contrato. Teste mais um criativo nessa linha.',
        ia: { active: 2, handoffs: 1, reviews: 2, conf: 81, resp: '2 min', csat: '4,8' },
        ticker: [
          { t: '10:05', x: 'Cibelle sugeriu resposta para <b>Paulo Henrique</b> · Transportadora PH' },
          { t: '09:40', x: 'Perfil de <b>Simone Araújo</b> enviado para análise' },
        ],
        alerts: [{ cls: 'cy', ic: 'ShieldCheck', t: 'Modo copiloto ativo: a Cibelle sugere e a equipe envia', go: 'sdr' }],
      },
      pipelines: [
        { id: 'pj', nm: 'Crédito PJ', desc: 'Do primeiro contato ao contrato', stages: [
          { id: 'novo', nm: 'Novo contato', p: 5 }, { id: 'necessidade', nm: 'Entendendo a necessidade', p: 15 }, { id: 'perfil', nm: 'Análise de perfil', p: 35 },
          { id: 'proposta', nm: 'Proposta de crédito', p: 60 }, { id: 'contratado', nm: 'Contratado', p: 100, won: true } ] },
      ],
      contacts: [
        { id: 'k1', nm: 'Paulo Henrique Dias', co: 'Transportadora PH', seg: 'Logística', city: 'Guarulhos/SP', ph: '(11) 90000-2201', em: 'paulo@transph.exemplo', src: 'Meta · Capital de giro', owner: 'u3', life: 'Lead', score: 58, last: 'hoje 10:05' },
        { id: 'k2', nm: 'Simone Araújo', co: 'Araújo Distribuidora', seg: 'Distribuição', city: 'Campinas/SP', ph: '(19) 90000-2202', em: 'simone@araujodist.exemplo', src: 'Indicação', owner: 'u1', life: 'Qualificado', score: 76, last: 'hoje 09:40' },
        { id: 'k3', nm: 'Ricardo Lemos', co: 'Lemos Metalúrgica', seg: 'Indústria', city: 'Sorocaba/SP', ph: '(15) 90000-2203', em: 'ricardo@lemosmetal.exemplo', src: 'Meta · Recebíveis', owner: 'u1', life: 'Qualificado', score: 81, last: 'ontem 16:20' },
        { id: 'k4', nm: 'Aline Castro', co: 'Castro Alimentos', seg: 'Alimentos', city: 'Jundiaí/SP', ph: '(11) 90000-2204', em: 'aline@castroalimentos.exemplo', src: 'Meta · Capital de giro', owner: 'u3', life: 'Lead', score: 44, last: 'ontem 11:00' },
        { id: 'k5', nm: 'Marcelo Tavares', co: 'Tavares Engenharia', seg: 'Engenharia', city: 'São Paulo/SP', ph: '(11) 90000-2205', em: 'marcelo@tavareseng.exemplo', src: 'Indicação', owner: 'u1', life: 'Cliente', score: 92, last: '02/10' },
        { id: 'k6', nm: 'Cristina Melo', co: 'Melo Têxtil', seg: 'Têxtil', city: 'Americana/SP', ph: '(19) 90000-2206', em: 'cristina@melotextil.exemplo', src: 'Meta · Recebíveis', owner: 'u1', life: 'Qualificado', score: 70, last: 'seg 15:30' },
      ],
      deals: [
        { id: 'x1', c: 'k1', p: 'pj', s: 'novo', v: 120000, temp: 'morno', owner: 'u3', next: 'Entender para que é o capital', age: '20 min' },
        { id: 'x2', c: 'k4', p: 'pj', s: 'necessidade', v: 80000, temp: 'frio', owner: 'u3', next: 'Retomar conversa amanhã', age: '1 dia' },
        { id: 'x3', c: 'k2', p: 'pj', s: 'perfil', v: 250000, temp: 'quente', owner: 'u1', next: 'Perfil em análise', age: '3 h' },
        { id: 'x4', c: 'k6', p: 'pj', s: 'perfil', v: 150000, temp: 'morno', owner: 'u1', next: 'Aguardando faturamento dos últimos 12 meses', age: '2 dias' },
        { id: 'x5', c: 'k3', p: 'pj', s: 'proposta', v: 390000, temp: 'quente', owner: 'u1', next: 'Apresentar proposta qui 10:00', age: '1 dia' },
        { id: 'x6', c: 'k5', p: 'pj', s: 'contratado', v: 185000, temp: 'quente', owner: 'u1', next: 'Contrato assinado em 02/10', age: '5 dias' },
      ],
      instances: [
        { id: 'j1', nm: 'Crédito Lothem', type: 'oficial', num: '+55 11 4000-0001', st: 'on', quality: 'Alta', tier: '250 conversas iniciadas / 24 h', today: 41, agents: ['ia', 'u1', 'u3'], use: 'Atendimento de quem chega pelos anúncios de crédito.' },
      ],
      templates: [
        { nm: 'retomar_conversa_credito', cat: 'Utilidade', st: 'Aprovado', lang: 'pt_BR', body: 'Oi, {{1}}. Conseguiu separar o faturamento dos últimos 12 meses?' },
      ],
      integrations: [
        { lg: 'M', nm: 'Meta Lead Ads', d: 'Leads dos anúncios de crédito.', st: 'on' },
        { lg: 'G', nm: 'Google Agenda', d: 'Reuniões de apresentação de proposta.', st: 'on' },
      ],
      conversations: [
        { id: 'cx1', c: 'k1', inst: 'j1', st: 'humano', who: 'u3', unread: 1, t: '10:05', slaType: 'retorno', slaSince: '10:05', conf: 79, q: { dor: 'Precisa de capital de giro para comprar 2 caminhões.' }, msgs: [
          { f: 'lead', x: 'Bom dia, preciso de capital de giro, vocês conseguem?', t: '10:01' },
          { f: 'user', u: 'u3', viaIa: true, x: 'Bom dia, Paulo! Aqui é a Marina, da Lothem Crédito.\nPra eu entender melhor: esse capital seria pra quê, exatamente?', t: '10:02' },
          { f: 'lead', x: 'Quero comprar 2 caminhões pra frota', t: '10:05' },
          { f: 'sys', x: 'Modo copiloto: a Cibelle preparou sugestões de resposta', t: '10:05' },
        ] },
        { id: 'cx2', c: 'k2', inst: 'j1', st: 'humano', who: 'u1', unread: 0, t: '09:40', conf: 0, q: { dor: 'Estoque maior para o fim de ano.', decisor: 'Simone e o diretor financeiro.', momento: 'Até novembro.' }, msgs: [
          { f: 'user', u: 'u1', x: 'Simone, recebi os documentos pelo canal seguro. Vou levar para análise hoje e te dou retorno até sexta.', t: '09:40' },
          { f: 'lead', x: 'Combinado, obrigada!', t: '09:42' },
        ] },
      ],
      tasks: [
        { id: 'y1', t: 'Retorno da análise de perfil · Araújo Distribuidora', type: 'Phone', who: 'u1', due: 2, at: '10:00', deal: 'x3', pri: 'alta', xp: 10 },
        { id: 'y2', t: 'Apresentar proposta · Lemos Metalúrgica', type: 'Video', who: 'u1', due: 1, at: '10:00', deal: 'x5', pri: 'alta', xp: 10 },
        { id: 'y3', t: 'Retomar conversa com Aline Castro', type: 'MessageCircle', who: 'u3', due: 1, at: '09:30', deal: 'x2', pri: 'média', xp: 10 },
      ],
      channels: [
        { id: 'geral', nm: 'geral', unread: 0, msgs: [{ day: 'Hoje' }, { u: 'u1', t: '08:10', x: 'Lembrete: nada de prometer taxa ou prazo de aprovação. A Cibelle está no copiloto até revisarmos as respostas.' }] },
      ],
      dms: [],
      kb: [
        { id: 'q1', ic: 'FileText', nm: 'Política comercial de crédito PJ', type: 'PDF · 9 páginas', cat: 'Treinamento', st: 'ok', uses: 210, upd: '15/09' },
        { id: 'q2', ic: 'ShieldCheck', nm: 'O que a Cibelle nunca pode dizer (taxa, prazo, aprovação)', type: 'Documento', cat: 'Regras', st: 'ok', uses: 340, upd: '15/09' },
        { id: 'q3', ic: 'CircleHelp', nm: 'Perguntas frequentes de capital de giro', type: 'Documento', cat: 'FAQ', st: 'ok', uses: 128, upd: '22/09' },
      ],
      skills: [
        { nm: 'Abertura', v: 90 }, { nm: 'Entender a necessidade', v: 78 }, { nm: 'Explicar o processo', v: 74 }, { nm: 'Cuidados legais', v: 96 }, { nm: 'Agendamento', v: 82 }, { nm: 'Fora do escopo', v: 61 },
      ],
      iaStats: { convs: 112, qual: '51,8%', sold: 0, soloSold: 0, transfers: 31, conf: 81, csat: '4,8', approvals: 18 },
      reviews: [
        { id: 'w1', who: 'Paulo Henrique Dias', co: 'Transportadora PH', q: 'Qual a taxa de juros?', a: 'As taxas começam em 1,2% ao mês.', conf: 41, why: 'Taxa não cadastrada. A resposta foi retida e não chegou ao lead.', skill: 'Cuidados legais', sent: false, blocked: true,
          ideal: 'A taxa depende da análise do perfil da empresa, Paulo, então eu não consigo te passar um número agora.\nO primeiro passo é entender o que vocês precisam. Posso te fazer 3 perguntas rápidas?' },
        { id: 'w2', who: 'Aline Castro', co: 'Castro Alimentos', q: 'Em quanto tempo sai o dinheiro?', a: 'Normalmente em 5 dias úteis.', conf: 48, why: 'Promessa de prazo', skill: 'Cuidados legais', sent: false, blocked: true,
          ideal: 'O prazo depende da análise e da instituição, Aline. O que eu consigo é te dizer em que etapa está o seu pedido a cada passo.' },
      ],
      rules: [
        { on: true, t: 'Nunca prometer aprovação, taxa, prazo ou limite', d: 'Regra obrigatória para serviços financeiros.', lock: true },
        { on: true, t: 'Não pedir documentos pelo WhatsApp', d: 'Documentos só pelo canal seguro definido pela equipe (LGPD).', lock: true },
        { on: true, t: 'Dizer que é assistente virtual', d: 'A Cibelle se apresenta como assistente virtual.', lock: true },
        { on: true, t: 'Modo copiloto obrigatório', d: 'Toda resposta da Cibelle passa por uma pessoa antes de sair.' },
      ],
      handoffRules: ['Qualquer pergunta sobre taxa, prazo ou aprovação', 'O cliente pede para falar com uma pessoa', 'Envio de documentos'],
    },

    /* ======================= LOTHEM — CRÉDITO PF (campanhas para pessoa física) ======================= */
    pf: {
      id: 'pf', name: 'LOTHEM — Inteligência em Crédito · PF', short: 'Lothem Crédito PF', mark: 'PF', hue: 'ok', accent: '#3ddc97',
      plan: 'Profissional', members: ['u1', 'u3'],
      ia: { name: 'Cibelle', role: 'Assistente de crédito IA', mode: 'cop', offer: 'Simulação de crédito pessoal', price: 0 },
      sla: { primeira: 10, transfer: 15, retorno: 20, followup: 24, warnAt: 75, business: true, notifyBoss: true, redistribute: false, iaHold: false, roles: ['SDR'] },
      slaStats: [
        { u: 'u3', convs: 142, inSla: 89, avg: '9 min 10 s', breaches: 12 },
        { u: 'u1', convs: 20, inSla: 95, avg: '4 min 30 s', breaches: 1 },
      ],
      autofill: {
        on: false, minConf: 90,
        fields: [
          { k: 'cadastro', nm: 'Cadastro do contato', d: 'Ocupação, cidade e e-mail que a pessoa conta na conversa.', on: true },
          { k: 'qualif', nm: 'Necessidade de crédito', d: 'Para que é o dinheiro, prazo e quem decide junto.', on: true },
          { k: 'score', nm: 'Pontuação', d: 'Recalcula a cada resposta.', on: false },
          { k: 'etapa', nm: 'Etapa do funil', d: 'Move o negócio quando a conversa avança.', on: false },
          { k: 'task', nm: 'Tarefas e agenda', d: 'Cria o retorno combinado.', on: true },
        ],
        never: ['CPF, RG, holerite ou fotos de documentos', 'Dados bancários e senhas', 'Taxa, prazo, valor ou aprovação'],
        stats: { today: 0, corrected: 0 },
        log: [],
      },
      route: {
        cpl: 8.96, outbound: 50, rateNote: 'Taxas dos últimos 30 dias · valor médio por contrato R$ 18.000 (fictício)',
        steps: [
          { k: 'contatos', nm: 'Contatos das campanhas PF', ic: 'UserPlus', who: ['ia', 'u3'], mtd: 104, r: 0.48, verb: 'explicam a necessidade' },
          { k: 'necessidade', nm: 'Necessidade entendida', ic: 'ListChecks', who: ['u3'], mtd: 50, r: 0.62, verb: 'recebem a simulação' },
          { k: 'simulacao', nm: 'Simulações feitas', one: 'simulação feita', ic: 'Calculator', who: ['u3'], mtd: 31, r: 0.4, verb: 'mandam os documentos' },
          { k: 'documentacao', nm: 'Documentos no canal seguro', ic: 'ShieldCheck', who: ['u1'], mtd: 12, r: 0.43, verb: 'assinam o contrato' },
          { k: 'contratado', nm: 'Contratos fechados', one: 'contrato fechado', ic: 'BadgeCheck', who: ['u1'], mtd: 4, value: 18000 },
        ],
        sdr: 'u3', closer: 'u1', sdrStep: 'simulacao', closerStep: 'contratado', closerPrep: 'documentacao',
      },
      metrics: {
        goalLabel: 'Volume contratado PF em outubro', goal: 250000, done: 64000, money: true,
        kpis: [
          { k: 'Contatos PF', v: '104', sub: 'no mês', delta: 18, spark: [16, 17, 14, 15, 16, 15, 11], go: 'contatos', hint: 'CPL médio R$ 8,96' },
          { k: 'Simulações feitas', v: '31', delta: 9, spark: [4, 5, 4, 5, 4, 5, 4], go: 'funis', hint: '62% de quem explicou a necessidade' },
          { k: 'Contratos', v: '4', sub: 'de 15', delta: 0, spark: [0, 1, 0, 1, 1, 0, 1], go: 'funis', hint: 'R$ 64 mil contratados' },
          { k: 'Primeira resposta', v: '3', unit: 'min', delta: 12, spark: [6, 5, 5, 4, 4, 3, 3], go: 'sdr', hint: 'Cibelle no modo copiloto', invert: true },
        ],
        funnel: [
          { nm: 'Contatos das campanhas', v: 412 }, { nm: 'Necessidade entendida', v: 198 }, { nm: 'Simulação feita', v: 122 }, { nm: 'Documentos enviados', v: 49 }, { nm: 'Contratado', v: 21, gold: true },
        ],
        funnelNote: 'Últimos 30 dias · campanhas PF · sem promessa de aprovação, taxa ou prazo',
        series: {
          a: [12, 14, 11, 15, 13, 10, 9, 14, 16, 13, 15, 12, 11, 16, 14, 15, 13, 17, 14, 12, 15, 14, 13, 16, 17, 14, 15, 16, 15, 11],
          b: [6, 7, 5, 7, 6, 5, 4, 7, 8, 6, 7, 6, 5, 8, 7, 7, 6, 8, 7, 6, 7, 7, 6, 8, 8, 7, 7, 8, 7, 5],
          la: 'Contatos', lb: 'Necessidade entendida', start: [8, 9],
        },
        campaigns: [
          { nm: '[PF] Crédito pessoal · Vídeo depoimento', inv: 1960, leads: 214, q: 109, d: 68, c: 12 },
          { nm: '[PF] Consignado INSS · Carrossel', inv: 1320, leads: 151, q: 71, d: 44, c: 8 },
          { nm: '[PF] Remarketing do simulador', inv: 410, leads: 47, q: 18, d: 10, c: 1 },
        ],
        campaignCols: ['Necessidade', 'Simulações', 'Contratos'], costLabel: 'simulação',
        insight: 'O vídeo de depoimento traz o contato mais barato (R$ 9,16) e 57% dos contratos. Vale testar mais um depoimento.',
        ia: { active: 3, handoffs: 0, reviews: 1, conf: 84, resp: '3 min', csat: '4,6' },
        ticker: [
          { t: '10:21', x: 'Cibelle sugeriu resposta para <b>Luciana Prado</b> · quitar o cartão' },
          { t: '10:02', x: '<b>Roberto Silva</b> enviou documentos pelo canal seguro', cls: 'ok' },
          { t: '09:42', x: 'Simulação de <b>André Costa</b> em preparo' },
        ],
        alerts: [],
      },
      pipelines: [
        { id: 'pf', nm: 'Funil PF · Campanhas', desc: 'Pessoa física que chega pelos anúncios, até o contrato', stages: [
          { id: 'novo', nm: 'Novo contato', p: 5 }, { id: 'necessidade', nm: 'Entendendo a necessidade', p: 15 }, { id: 'simulacao', nm: 'Simulação feita', p: 35 },
          { id: 'documentacao', nm: 'Documentos no canal seguro', p: 60 }, { id: 'contratado', nm: 'Contratado', p: 100, won: true }, { id: 'perdido', nm: 'Perdido', p: 0, lost: true } ] },
      ],
      contacts: [
        { id: 'p1', pf: true, nm: 'Luciana Prado', co: 'Professora da rede estadual', seg: 'Crédito pessoal', city: 'Campinas/SP', ph: '(19) 90000-3101', em: 'luciana.prado@exemplo.com', src: 'Meta · [PF] Vídeo depoimento', owner: 'u3', life: 'Lead', score: 52, last: 'hoje 10:21' },
        { id: 'p2', pf: true, nm: 'Roberto Silva', co: 'Aposentado do INSS', seg: 'Consignado', city: 'Santo André/SP', ph: '(11) 90000-3102', em: 'roberto.silva@exemplo.com', src: 'Meta · [PF] Consignado INSS', owner: 'u1', life: 'Qualificado', score: 84, last: 'hoje 10:09' },
        { id: 'p3', pf: true, nm: 'Camila Freitas', co: 'Enfermeira', seg: 'Crédito pessoal', city: 'Osasco/SP', ph: '(11) 90000-3103', em: 'camila.freitas@exemplo.com', src: 'Meta · [PF] Vídeo depoimento', owner: 'u3', life: 'Qualificado', score: 71, last: 'ontem 19:40' },
        { id: 'p4', pf: true, nm: 'José Antunes', co: 'Motorista de aplicativo', seg: 'Refinanciamento', city: 'São Paulo/SP', ph: '(11) 90000-3104', em: 'jose.antunes@exemplo.com', src: 'Meta · [PF] Remarketing do simulador', owner: 'u3', life: 'Lead', score: 38, last: 'ontem 15:10' },
        { id: 'p5', pf: true, nm: 'Márcia Lopes', co: 'Servidora municipal', seg: 'Consignado', city: 'Guarulhos/SP', ph: '(11) 90000-3105', em: 'marcia.lopes@exemplo.com', src: 'Meta · [PF] Consignado INSS', owner: 'u1', life: 'Cliente', score: 93, last: '05/10' },
        { id: 'p6', pf: true, nm: 'André Costa', co: 'Eletricista autônomo', seg: 'Crédito pessoal', city: 'Jundiaí/SP', ph: '(11) 90000-3106', em: 'andre.costa@exemplo.com', src: 'Meta · [PF] Vídeo depoimento', owner: 'u3', life: 'Lead', score: 45, last: 'hoje 09:42' },
        { id: 'p7', pf: true, nm: 'Helena Martins', co: 'Aposentada do INSS', seg: 'Consignado', city: 'Sorocaba/SP', ph: '(15) 90000-3107', em: 'helena.martins@exemplo.com', src: 'Meta · [PF] Consignado INSS', owner: 'u1', life: 'Qualificado', score: 79, last: 'seg 11:30' },
        { id: 'p8', pf: true, nm: 'Fábio Reis', co: 'Vendedor', seg: 'Crédito pessoal', city: 'Barueri/SP', ph: '(11) 90000-3108', em: 'fabio.reis@exemplo.com', src: 'Meta · [PF] Vídeo depoimento', owner: 'u3', life: 'Perdido', score: 30, last: '30/09' },
      ],
      deals: [
        { id: 'y1', c: 'p6', p: 'pf', s: 'novo', v: 8000, temp: 'frio', owner: 'u3', next: 'Montar a simulação', age: 'hoje' },
        { id: 'y2', c: 'p1', p: 'pf', s: 'necessidade', v: 15000, temp: 'morno', owner: 'u3', next: 'Entender quanto deve no cartão', age: '9 min', flag: 'Responder' },
        { id: 'y3', c: 'p4', p: 'pf', s: 'necessidade', v: 12000, temp: 'frio', owner: 'u3', next: 'Retomar amanhã às 9h', age: '1 dia' },
        { id: 'y4', c: 'p3', p: 'pf', s: 'simulacao', v: 20000, temp: 'morno', owner: 'u3', next: 'Enviar simulação revisada', age: '1 dia' },
        { id: 'y5', c: 'p7', p: 'pf', s: 'simulacao', v: 25000, temp: 'quente', owner: 'u1', next: 'Tirar dúvidas sobre parcelas', age: '2 dias' },
        { id: 'y6', c: 'p2', p: 'pf', s: 'documentacao', v: 30000, temp: 'quente', owner: 'u1', next: 'Documentos em análise', age: 'hoje' },
        { id: 'y7', c: 'p5', p: 'pf', s: 'contratado', v: 18000, temp: 'quente', owner: 'u1', next: 'Contrato assinado em 05/10', age: '2 dias' },
        { id: 'y8', c: 'p8', p: 'pf', s: 'perdido', v: 10000, temp: 'frio', owner: 'u3', next: 'Motivo: sem margem disponível', age: '7 dias' },
      ],
      instances: [
        { id: 'k1', nm: 'Crédito PF', type: 'oficial', num: '+55 11 4000-0002', st: 'on', quality: 'Média', tier: '250 conversas iniciadas / 24 h', today: 96, agents: ['ia', 'u3', 'u1'], use: 'Atendimento das campanhas PF. A Cibelle sugere e a equipe envia.' },
      ],
      templates: [
        { nm: 'simulacao_pronta', cat: 'Utilidade', st: 'Aprovado', lang: 'pt_BR', body: 'Oi, {{1}}! Sua simulação ficou pronta. Posso te explicar as condições por aqui?' },
        { nm: 'documentos_canal_seguro', cat: 'Utilidade', st: 'Aprovado', lang: 'pt_BR', body: '{{1}}, os documentos são enviados só por este link seguro: {{2}}. Não mande foto de documento pelo WhatsApp.' },
      ],
      integrations: [
        { lg: 'M', nm: 'Meta Lead Ads', d: 'Leads das campanhas PF.', st: 'on' },
        { lg: 'S', nm: 'Simulador de crédito', d: 'Gera a simulação e anexa ao negócio.', st: 'on' },
        { lg: 'D', nm: 'Canal seguro de documentos', d: 'Recebe RG, CPF e holerite fora do WhatsApp (LGPD).', st: 'on' },
      ],
      conversations: [
        { id: 'pv1', c: 'p1', inst: 'k1', st: 'humano', who: 'u3', unread: 1, t: '10:21', slaType: 'retorno', slaSince: '10:21', conf: 82, q: { dor: 'Quer quitar o cartão de crédito, que está com juros altos.' }, msgs: [
          { f: 'lead', x: 'Oi, vi o anúncio do crédito pessoal. Quanto eu consigo?', t: '10:15' },
          { f: 'user', u: 'u3', viaIa: true, x: 'Oi, Luciana! Aqui é a Marina, da Lothem Crédito.\nO valor depende de uma análise, então não consigo te passar um número agora. Me conta: pra que você precisa do crédito?', t: '10:17' },
          { f: 'lead', x: 'Quero quitar o cartão, os juros tão me matando', t: '10:21' },
          { f: 'sys', x: 'Modo copiloto: a Cibelle preparou sugestões de resposta', t: '10:21' },
        ] },
        { id: 'pv2', c: 'p2', inst: 'k1', st: 'humano', who: 'u1', unread: 0, t: '10:09', conf: 0, q: { dor: 'Consignado para reformar a casa.', decisor: 'Ele e a esposa.', momento: 'Este mês.' }, msgs: [
          { f: 'sys', x: 'Documentos recebidos pelo canal seguro · RG, CPF e extrato do INSS', t: '10:02', cls: 'ok' },
          { f: 'user', u: 'u1', x: 'Seu Roberto, recebi os documentos certinho. Agora vai para análise e eu te dou retorno até sexta.', t: '10:05' },
          { f: 'lead', x: 'Obrigado, minha filha. Fico no aguardo', t: '10:09' },
        ] },
        { id: 'pv3', c: 'p6', inst: 'k1', st: 'humano', who: 'u3', unread: 0, t: '09:42', conf: 88, q: { dor: 'Comprar ferramentas novas para o trabalho.' }, msgs: [
          { f: 'lead', x: 'Bom dia, sou autônomo, consigo crédito?', t: '09:15' },
          { f: 'user', u: 'u3', viaIa: true, x: 'Bom dia, André! Dá para fazer a análise sendo autônomo, sim. Pra eu entender melhor: o crédito seria pra quê?', t: '09:18' },
          { f: 'lead', x: 'Comprar ferramentas novas', t: '09:40' },
          { f: 'user', u: 'u3', x: 'Boa! Vou te mandar umas perguntas rápidas pra montar a simulação.', t: '09:42' },
        ] },
      ],
      tasks: [
        { id: 'z4', t: 'Enviar simulação revisada para Camila Freitas', type: 'FileText', who: 'u3', due: 0, at: '11:30', deal: 'y4', pri: 'alta', xp: 10 },
        { id: 'z2', t: 'Tirar dúvidas de parcelas com Helena Martins', type: 'Phone', who: 'u1', due: 0, at: '15:00', deal: 'y5', pri: 'média', xp: 10 },
        { id: 'z3', t: 'Retomar conversa com José Antunes', type: 'MessageCircle', who: 'u3', due: 1, at: '09:00', deal: 'y3', pri: 'média', xp: 10 },
        { id: 'z1', t: 'Retorno da análise · Roberto Silva', type: 'Phone', who: 'u1', due: 2, at: '10:00', deal: 'y6', pri: 'alta', xp: 10 },
      ],
      channels: [
        { id: 'geral', nm: 'geral', unread: 0, msgs: [{ day: 'Hoje' },
          { u: 'u1', t: '08:15', x: 'Campanha PF: o vídeo de depoimento está trazendo o contato mais barato. Lembrando: documento só pelo canal seguro, nunca pelo WhatsApp.' },
          { u: 'u3', t: '08:31', x: 'Combinado. Hoje tenho 3 simulações para mandar.' }] },
      ],
      dms: [],
      kb: [
        { id: 'f1', ic: 'FileText', nm: 'Política de crédito pessoal e consignado', type: 'PDF · 12 páginas', cat: 'Treinamento', st: 'ok', uses: 180, upd: '20/09' },
        { id: 'f2', ic: 'ShieldCheck', nm: 'O que a Cibelle nunca diz (taxa, prazo, valor, aprovação)', type: 'Documento', cat: 'Regras', st: 'ok', uses: 260, upd: '20/09' },
        { id: 'f3', ic: 'CircleHelp', nm: 'Perguntas frequentes de consignado INSS', type: 'Documento', cat: 'FAQ', st: 'ok', uses: 95, upd: '01/10' },
      ],
      skills: [
        { nm: 'Abertura', v: 88 }, { nm: 'Entender a necessidade', v: 80 }, { nm: 'Explicar a simulação', v: 72 }, { nm: 'Cuidados legais', v: 97 }, { nm: 'Canal seguro de documentos', v: 93 }, { nm: 'Fora do escopo', v: 60 },
      ],
      iaStats: { convs: 412, qual: '48,1%', sold: 0, soloSold: 0, transfers: 58, conf: 84, csat: '4,6', approvals: 11 },
      reviews: [
        { id: 'v1', who: 'José Antunes', co: 'Motorista de aplicativo', q: 'Com nome sujo eu consigo?', a: 'Consegue sim, temos opções para negativados.', conf: 44, why: 'Promessa de aprovação. A resposta foi retida e não chegou ao lead.', skill: 'Cuidados legais', sent: false, blocked: true,
          ideal: 'Dá para fazer a análise mesmo com restrição no nome, José. Se aprova ou não, só a análise diz.\nQuer que eu te explique como funciona?' },
      ],
      rules: [
        { on: true, t: 'Nunca prometer aprovação, taxa, prazo ou valor', d: 'Regra obrigatória para serviços financeiros.', lock: true },
        { on: true, t: 'Documentos só pelo canal seguro', d: 'Nada de foto de RG, CPF ou holerite pelo WhatsApp (LGPD).', lock: true },
        { on: true, t: 'Dizer que é assistente virtual', d: 'A Cibelle se apresenta como assistente virtual.', lock: true },
        { on: true, t: 'Atenção a sinal de superendividamento', d: 'Se a pessoa contar que já está com muitas dívidas, a Cibelle entende a situação antes de falar de crédito e chama alguém do time.', lock: true },
        { on: true, t: 'Modo copiloto obrigatório', d: 'Toda resposta da Cibelle passa por uma pessoa antes de sair.' },
      ],
      handoffRules: ['Pergunta sobre taxa, prazo, valor ou aprovação', 'A pessoa pede para falar com alguém', 'Envio de documentos', 'Sinal de superendividamento'],
    },
  },
};
